UPDATE `mob_db` SET `kName` = "Escorpião", `iName` = "Escorpião" WHERE `ID` = 1001;
UPDATE `mob_db` SET `kName` = "Poring", `iName` = "Poring" WHERE `ID` = 1002;
UPDATE `mob_db` SET `kName` = "Zangão", `iName` = "Zangão" WHERE `ID` = 1004;
UPDATE `mob_db` SET `kName` = "Familiar", `iName` = "Familiar" WHERE `ID` = 1005;
UPDATE `mob_db` SET `kName` = "Fabre", `iName` = "Fabre" WHERE `ID` = 1007;
UPDATE `mob_db` SET `kName` = "Pupa", `iName` = "Pupa" WHERE `ID` = 1008;
UPDATE `mob_db` SET `kName` = "Condor", `iName` = "Condor" WHERE `ID` = 1009;
UPDATE `mob_db` SET `kName` = "Salgueiro", `iName` = "Salgueiro" WHERE `ID` = 1010;
UPDATE `mob_db` SET `kName` = "ChonChon", `iName` = "ChonChon" WHERE `ID` = 1011;
UPDATE `mob_db` SET `kName` = "Sapo de Roda", `iName` = "Sapo de Roda" WHERE `ID` = 1012;
UPDATE `mob_db` SET `kName` = "Lobo", `iName` = "Lobo" WHERE `ID` = 1013;
UPDATE `mob_db` SET `kName` = "Esporo", `iName` = "Esporo" WHERE `ID` = 1014;
UPDATE `mob_db` SET `kName` = "Zumbi", `iName` = "Zumbi" WHERE `ID` = 1015;
UPDATE `mob_db` SET `kName` = "Esqueleto Arqueiro", `iName` = "Esqueleto Arqueiro" WHERE `ID` = 1016;
UPDATE `mob_db` SET `kName` = "Creamy", `iName` = "Creamy" WHERE `ID` = 1018;
UPDATE `mob_db` SET `kName` = "Peco Peco", `iName` = "Peco Peco" WHERE `ID` = 1019;
UPDATE `mob_db` SET `kName` = "Mandrágora", `iName` = "Mandrágora" WHERE `ID` = 1020;
UPDATE `mob_db` SET `kName` = "Guerreiro Orc", `iName` = "Guerreiro Orc" WHERE `ID` = 1023;
UPDATE `mob_db` SET `kName` = "Rabo de Verme", `iName` = "Rabo de Verme" WHERE `ID` = 1024;
UPDATE `mob_db` SET `kName` = "Jibóia", `iName` = "Jibóia" WHERE `ID` = 1025;
UPDATE `mob_db` SET `kName` = "Munak", `iName` = "Munak" WHERE `ID` = 1026;
UPDATE `mob_db` SET `kName` = "Esqueleto Soldado", `iName` = "Esqueleto Soldado" WHERE `ID` = 1028;
UPDATE `mob_db` SET `kName` = "Isis", `iName` = "Isis" WHERE `ID` = 1029;
UPDATE `mob_db` SET `kName` = "Anaconda", `iName` = "Anaconda" WHERE `ID` = 1030;
UPDATE `mob_db` SET `kName` = "Poporing", `iName` = "Poporing" WHERE `ID` = 1031;
UPDATE `mob_db` SET `kName` = "Verit", `iName` = "Verit" WHERE `ID` = 1032;
UPDATE `mob_db` SET `kName` = "Salgueiro Ancião", `iName` = "Salgueiro Ancião" WHERE `ID` = 1033;
UPDATE `mob_db` SET `kName` = "Sapo de Thara", `iName` = "Sapo de Thara" WHERE `ID` = 1034;
UPDATE `mob_db` SET `kName` = "Mosca Caçadora", `iName` = "Mosca Caçadora" WHERE `ID` = 1035;
UPDATE `mob_db` SET `kName` = "Carniçal", `iName` = "Carniçal" WHERE `ID` = 1036;
UPDATE `mob_db` SET `kName` = "Sorrateiro", `iName` = "Sorrateiro" WHERE `ID` = 1037;
UPDATE `mob_db` SET `kName` = "Osíris", `iName` = "Osíris" WHERE `ID` = 1038;
UPDATE `mob_db` SET `kName` = "Bafomé", `iName` = "Bafomé" WHERE `ID` = 1039;
UPDATE `mob_db` SET `kName` = "Golem", `iName` = "Golem" WHERE `ID` = 1040;
UPDATE `mob_db` SET `kName` = "Múmia", `iName` = "Múmia" WHERE `ID` = 1041;
UPDATE `mob_db` SET `kName` = "Chonchon de Aço", `iName` = "Chonchon de Aço" WHERE `ID` = 1042;
UPDATE `mob_db` SET `kName` = "Obeaune", `iName` = "Obeaune" WHERE `ID` = 1044;
UPDATE `mob_db` SET `kName` = "Cavalo-Marinho", `iName` = "Cavalo-Marinho" WHERE `ID` = 1045;
UPDATE `mob_db` SET `kName` = "Doppelganger", `iName` = "Doppelganger" WHERE `ID` = 1046;
UPDATE `mob_db` SET `kName` = "Ovo de Peco Peco", `iName` = "Ovo de Peco Peco" WHERE `ID` = 1047;
UPDATE `mob_db` SET `kName` = "Ovo de Besouro-Ladrão", `iName` = "Ovo de Besouro-Ladrão" WHERE `ID` = 1048;
UPDATE `mob_db` SET `kName` = "Picky", `iName` = "Picky" WHERE `ID` = 1049;
UPDATE `mob_db` SET `kName` = "Picky com Casca", `iName` = "Picky com Casca" WHERE `ID` = 1050;
UPDATE `mob_db` SET `kName` = "Besouro-Ladrão", `iName` = "Besouro-Ladrão" WHERE `ID` = 1051;
UPDATE `mob_db` SET `kName` = "Rocker", `iName` = "Rocker" WHERE `ID` = 1052;
UPDATE `mob_db` SET `kName` = "Besouro-Ladrão Fêmea", `iName` = "Besouro-Ladrão Fêmea" WHERE `ID` = 1053;
UPDATE `mob_db` SET `kName` = "Besouro-Ladrão Macho", `iName` = "Besouro-Ladrão Macho" WHERE `ID` = 1054;
UPDATE `mob_db` SET `kName` = "Muka", `iName` = "Muka" WHERE `ID` = 1055;
UPDATE `mob_db` SET `kName` = "Fumacento", `iName` = "Fumacento" WHERE `ID` = 1056;
UPDATE `mob_db` SET `kName` = "Yoyo", `iName` = "Yoyo" WHERE `ID` = 1057;
UPDATE `mob_db` SET `kName` = "Metaller", `iName` = "Metaller" WHERE `ID` = 1058;
UPDATE `mob_db` SET `kName` = "Abelha-Rainha", `iName` = "Abelha-Rainha" WHERE `ID` = 1059;
UPDATE `mob_db` SET `kName` = "Pé Grande", `iName` = "Pé Grande" WHERE `ID` = 1060;
UPDATE `mob_db` SET `kName` = "Pesadelo", `iName` = "Pesadelo" WHERE `ID` = 1061;
UPDATE `mob_db` SET `kName` = "Poring Noel", `iName` = "Poring Noel" WHERE `ID` = 1062;
UPDATE `mob_db` SET `kName` = "Lunático", `iName` = "Lunático" WHERE `ID` = 1063;
UPDATE `mob_db` SET `kName` = "Megalodon", `iName` = "Megalodon" WHERE `ID` = 1064;
UPDATE `mob_db` SET `kName` = "Strouf", `iName` = "Strouf" WHERE `ID` = 1065;
UPDATE `mob_db` SET `kName` = "Vadon", `iName` = "Vadon" WHERE `ID` = 1066;
UPDATE `mob_db` SET `kName` = "Cornutus", `iName` = "Cornutus" WHERE `ID` = 1067;
UPDATE `mob_db` SET `kName` = "Hidra", `iName` = "Hidra" WHERE `ID` = 1068;
UPDATE `mob_db` SET `kName` = "Peixe-Espada", `iName` = "Peixe-Espada" WHERE `ID` = 1069;
UPDATE `mob_db` SET `kName` = "Kukre", `iName` = "Kukre" WHERE `ID` = 1070;
UPDATE `mob_db` SET `kName` = "Esqueleto Pirata", `iName` = "Esqueleto Pirata" WHERE `ID` = 1071;
UPDATE `mob_db` SET `kName` = "Kaho", `iName` = "Kaho" WHERE `ID` = 1072;
UPDATE `mob_db` SET `kName` = "Caranguejo", `iName` = "Caranguejo" WHERE `ID` = 1073;
UPDATE `mob_db` SET `kName` = "Molusco", `iName` = "Molusco" WHERE `ID` = 1074;
UPDATE `mob_db` SET `kName` = "Esqueleto", `iName` = "Esqueleto" WHERE `ID` = 1076;
UPDATE `mob_db` SET `kName` = "Esporo Venenoso", `iName` = "Esporo Venenoso" WHERE `ID` = 1077;
UPDATE `mob_db` SET `kName` = "Planta Vermelha", `iName` = "Planta Vermelha" WHERE `ID` = 1078;
UPDATE `mob_db` SET `kName` = "Planta Azul", `iName` = "Planta Azul" WHERE `ID` = 1079;
UPDATE `mob_db` SET `kName` = "Planta Verde", `iName` = "Planta Verde" WHERE `ID` = 1080;
UPDATE `mob_db` SET `kName` = "Planta Amarela", `iName` = "Planta Amarela" WHERE `ID` = 1081;
UPDATE `mob_db` SET `kName` = "Planta Branca", `iName` = "Planta Branca" WHERE `ID` = 1082;
UPDATE `mob_db` SET `kName` = "Planta Brilhante", `iName` = "Planta Brilhante" WHERE `ID` = 1083;
UPDATE `mob_db` SET `kName` = "Cogumelo Negro", `iName` = "Cogumelo Negro" WHERE `ID` = 1084;
UPDATE `mob_db` SET `kName` = "Cogumelo Vermelho", `iName` = "Cogumelo Vermelho" WHERE `ID` = 1085;
UPDATE `mob_db` SET `kName` = "Besouro-Ladrão Dourado", `iName` = "Besouro-Ladrão Dourado" WHERE `ID` = 1086;
UPDATE `mob_db` SET `kName` = "Orc Herói", `iName` = "Orc Herói" WHERE `ID` = 1087;
UPDATE `mob_db` SET `kName` = "Vocal", `iName` = "Vocal" WHERE `ID` = 1088;
UPDATE `mob_db` SET `kName` = "Sapo-Cururu", `iName` = "Sapo-Cururu" WHERE `ID` = 1089;
UPDATE `mob_db` SET `kName` = "Mastering", `iName` = "Mastering" WHERE `ID` = 1090;
UPDATE `mob_db` SET `kName` = "Libélula", `iName` = "Libélula" WHERE `ID` = 1091;
UPDATE `mob_db` SET `kName` = "Lobo Errante", `iName` = "Lobo Errante" WHERE `ID` = 1092;
UPDATE `mob_db` SET `kName` = "Eclipse", `iName` = "Eclipse" WHERE `ID` = 1093;
UPDATE `mob_db` SET `kName` = "Ambernite", `iName` = "Ambernite" WHERE `ID` = 1094;
UPDATE `mob_db` SET `kName` = "Andre", `iName` = "Andre" WHERE `ID` = 1095;
UPDATE `mob_db` SET `kName` = "Angeling", `iName` = "Angeling" WHERE `ID` = 1096;
UPDATE `mob_db` SET `kName` = "Ovo de Andre", `iName` = "Ovo de Andre" WHERE `ID` = 1097;
UPDATE `mob_db` SET `kName` = "Anubis", `iName` = "Anubis" WHERE `ID` = 1098;
UPDATE `mob_db` SET `kName` = "Argiope", `iName` = "Argiope" WHERE `ID` = 1099;
UPDATE `mob_db` SET `kName` = "Argos", `iName` = "Argos" WHERE `ID` = 1100;
UPDATE `mob_db` SET `kName` = "Bafomé Jr.", `iName` = "Bafomé Jr." WHERE `ID` = 1101;
UPDATE `mob_db` SET `kName` = "Bathory", `iName` = "Bathory" WHERE `ID` = 1102;
UPDATE `mob_db` SET `kName` = "Caramelo", `iName` = "Caramelo" WHERE `ID` = 1103;
UPDATE `mob_db` SET `kName` = "Koko", `iName` = "Koko" WHERE `ID` = 1104;
UPDATE `mob_db` SET `kName` = "Deniro", `iName` = "Deniro" WHERE `ID` = 1105;
UPDATE `mob_db` SET `kName` = "Lobo do Deserto", `iName` = "Lobo do Deserto" WHERE `ID` = 1106;
UPDATE `mob_db` SET `kName` = "Filhote de Lobo do Deserto", `iName` = "Filhote de Lobo do Deserto" WHERE `ID` = 1107;
UPDATE `mob_db` SET `kName` = "Deviace", `iName` = "Deviace" WHERE `ID` = 1108;
UPDATE `mob_db` SET `kName` = "Deviruchi", `iName` = "Deviruchi" WHERE `ID` = 1109;
UPDATE `mob_db` SET `kName` = "Dokebi", `iName` = "Dokebi" WHERE `ID` = 1110;
UPDATE `mob_db` SET `kName` = "Drainliar", `iName` = "Drainliar" WHERE `ID` = 1111;
UPDATE `mob_db` SET `kName` = "Drake", `iName` = "Drake" WHERE `ID` = 1112;
UPDATE `mob_db` SET `kName` = "Drops", `iName` = "Drops" WHERE `ID` = 1113;
UPDATE `mob_db` SET `kName` = "Poeira", `iName` = "Poeira" WHERE `ID` = 1114;
UPDATE `mob_db` SET `kName` = "Eddga", `iName` = "Eddga" WHERE `ID` = 1115;
UPDATE `mob_db` SET `kName` = "Eggyra", `iName` = "Eggyra" WHERE `ID` = 1116;
UPDATE `mob_db` SET `kName` = "Druida Maligno", `iName` = "Druida Maligno" WHERE `ID` = 1117;
UPDATE `mob_db` SET `kName` = "Flora", `iName` = "Flora" WHERE `ID` = 1118;
UPDATE `mob_db` SET `kName` = "Frilldora", `iName` = "Frilldora" WHERE `ID` = 1119;
UPDATE `mob_db` SET `kName` = "Ghostring", `iName` = "Ghostring" WHERE `ID` = 1120;
UPDATE `mob_db` SET `kName` = "Giearth", `iName` = "Giearth" WHERE `ID` = 1121;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1122;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1123;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1124;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1125;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1126;
UPDATE `mob_db` SET `kName` = "Hode", `iName` = "Hode" WHERE `ID` = 1127;
UPDATE `mob_db` SET `kName` = "Besouro-Chifre", `iName` = "Besouro-Chifre" WHERE `ID` = 1128;
UPDATE `mob_db` SET `kName` = "Horong", `iName` = "Horong" WHERE `ID` = 1129;
UPDATE `mob_db` SET `kName` = "Jakk", `iName` = "Jakk" WHERE `ID` = 1130;
UPDATE `mob_db` SET `kName` = "Coringa", `iName` = "Coringa" WHERE `ID` = 1131;
UPDATE `mob_db` SET `kName` = "Khalitzburg", `iName` = "Khalitzburg" WHERE `ID` = 1132;
UPDATE `mob_db` SET `kName` = "Cobold", `iName` = "Cobold" WHERE `ID` = 1133;
UPDATE `mob_db` SET `kName` = "Cobold", `iName` = "Cobold" WHERE `ID` = 1134;
UPDATE `mob_db` SET `kName` = "Cobold", `iName` = "Cobold" WHERE `ID` = 1135;
UPDATE `mob_db` SET `kName` = "Magnólia", `iName` = "Magnólia" WHERE `ID` = 1138;
UPDATE `mob_db` SET `kName` = "Louva-a-Deus", `iName` = "Louva-a-Deus" WHERE `ID` = 1139;
UPDATE `mob_db` SET `kName` = "Marduk", `iName` = "Marduk" WHERE `ID` = 1140;
UPDATE `mob_db` SET `kName` = "Marina", `iName` = "Marina" WHERE `ID` = 1141;
UPDATE `mob_db` SET `kName` = "Esfera Marinha", `iName` = "Esfera Marinha" WHERE `ID` = 1142;
UPDATE `mob_db` SET `kName` = "Marionete", `iName` = "Marionete" WHERE `ID` = 1143;
UPDATE `mob_db` SET `kName` = "Marte", `iName` = "Marte" WHERE `ID` = 1144;
UPDATE `mob_db` SET `kName` = "Martin", `iName` = "Martin" WHERE `ID` = 1145;
UPDATE `mob_db` SET `kName` = "Matyr", `iName` = "Matyr" WHERE `ID` = 1146;
UPDATE `mob_db` SET `kName` = "Maya", `iName` = "Maya" WHERE `ID` = 1147;
UPDATE `mob_db` SET `kName` = "Medusa", `iName` = "Medusa" WHERE `ID` = 1148;
UPDATE `mob_db` SET `kName` = "Minorous", `iName` = "Minorous" WHERE `ID` = 1149;
UPDATE `mob_db` SET `kName` = "Flor do Luar", `iName` = "Flor do Luar" WHERE `ID` = 1150;
UPDATE `mob_db` SET `kName` = "Névoa", `iName` = "Névoa" WHERE `ID` = 1151;
UPDATE `mob_db` SET `kName` = "Orc Esqueleto", `iName` = "Orc Esqueleto" WHERE `ID` = 1152;
UPDATE `mob_db` SET `kName` = "Orc Zumbi", `iName` = "Orc Zumbi" WHERE `ID` = 1153;
UPDATE `mob_db` SET `kName` = "Pasana", `iName` = "Pasana" WHERE `ID` = 1154;
UPDATE `mob_db` SET `kName` = "Petite", `iName` = "Petite" WHERE `ID` = 1155;
UPDATE `mob_db` SET `kName` = "Petite Voador", `iName` = "Petite Voador" WHERE `ID` = 1156;
UPDATE `mob_db` SET `kName` = "Faraó", `iName` = "Faraó" WHERE `ID` = 1157;
UPDATE `mob_db` SET `kName` = "Fen", `iName` = "Fen" WHERE `ID` = 1158;
UPDATE `mob_db` SET `kName` = "Freeoni", `iName` = "Freeoni" WHERE `ID` = 1159;
UPDATE `mob_db` SET `kName` = "Piere", `iName` = "Piere" WHERE `ID` = 1160;
UPDATE `mob_db` SET `kName` = "Plankton", `iName` = "Plankton" WHERE `ID` = 1161;
UPDATE `mob_db` SET `kName` = "Rafflesia", `iName` = "Rafflesia" WHERE `ID` = 1162;
UPDATE `mob_db` SET `kName` = "Raydric", `iName` = "Raydric" WHERE `ID` = 1163;
UPDATE `mob_db` SET `kName` = "Requiem", `iName` = "Requiem" WHERE `ID` = 1164;
UPDATE `mob_db` SET `kName` = "Arenoso", `iName` = "Arenoso" WHERE `ID` = 1165;
UPDATE `mob_db` SET `kName` = "Selvagem", `iName` = "Selvagem" WHERE `ID` = 1166;
UPDATE `mob_db` SET `kName` = "Bebê Selvagem", `iName` = "Bebê Selvagem" WHERE `ID` = 1167;
UPDATE `mob_db` SET `kName` = "Esqueleto Operário", `iName` = "Esqueleto Operário" WHERE `ID` = 1169;
UPDATE `mob_db` SET `kName` = "Sohee", `iName` = "Sohee" WHERE `ID` = 1170;
UPDATE `mob_db` SET `kName` = "Percevejo", `iName` = "Percevejo" WHERE `ID` = 1174;
UPDATE `mob_db` SET `kName` = "Tarou", `iName` = "Tarou" WHERE `ID` = 1175;
UPDATE `mob_db` SET `kName` = "Vitata", `iName` = "Vitata" WHERE `ID` = 1176;
UPDATE `mob_db` SET `kName` = "Zenorc", `iName` = "Zenorc" WHERE `ID` = 1177;
UPDATE `mob_db` SET `kName` = "Zerom", `iName` = "Zerom" WHERE `ID` = 1178;
UPDATE `mob_db` SET `kName` = "Sussurro", `iName` = "Sussurro" WHERE `ID` = 1179;
UPDATE `mob_db` SET `kName` = "Nove Caudas", `iName` = "Nove Caudas" WHERE `ID` = 1180;
UPDATE `mob_db` SET `kName` = "Cogumelo", `iName` = "Cogumelo" WHERE `ID` = 1182;
UPDATE `mob_db` SET `kName` = "Chonchon", `iName` = "Chonchon" WHERE `ID` = 1183;
UPDATE `mob_db` SET `kName` = "Fabre", `iName` = "Fabre" WHERE `ID` = 1184;
UPDATE `mob_db` SET `kName` = "Sussurro", `iName` = "Sussurro" WHERE `ID` = 1185;
UPDATE `mob_db` SET `kName` = "Cochicho", `iName` = "Cochicho" WHERE `ID` = 1186;
UPDATE `mob_db` SET `kName` = "Switch", `iName` = "Switch" WHERE `ID` = 1187;
UPDATE `mob_db` SET `kName` = "Bongun", `iName` = "Bongun" WHERE `ID` = 1188;
UPDATE `mob_db` SET `kName` = "Orc Arqueiro", `iName` = "Orc Arqueiro" WHERE `ID` = 1189;
UPDATE `mob_db` SET `kName` = "Senhor dos Orcs", `iName` = "Senhor dos Orcs" WHERE `ID` = 1190;
UPDATE `mob_db` SET `kName` = "Mímico", `iName` = "Mímico" WHERE `ID` = 1191;
UPDATE `mob_db` SET `kName` = "Alma Penada", `iName` = "Alma Penada" WHERE `ID` = 1192;
UPDATE `mob_db` SET `kName` = "Alarme", `iName` = "Alarme" WHERE `ID` = 1193;
UPDATE `mob_db` SET `kName` = "Arclouse", `iName` = "Arclouse" WHERE `ID` = 1194;
UPDATE `mob_db` SET `kName` = "Rideword", `iName` = "Rideword" WHERE `ID` = 1195;
UPDATE `mob_db` SET `kName` = "Esqueleto Prisioneiro", `iName` = "Esqueleto Prisioneiro" WHERE `ID` = 1196;
UPDATE `mob_db` SET `kName` = "Zumbi Prisioneiro", `iName` = "Zumbi Prisioneiro" WHERE `ID` = 1197;
UPDATE `mob_db` SET `kName` = "Sacerdote Maldito", `iName` = "Sacerdote Maldito" WHERE `ID` = 1198;
UPDATE `mob_db` SET `kName` = "Punk", `iName` = "Punk" WHERE `ID` = 1199;
UPDATE `mob_db` SET `kName` = "Jirtas", `iName` = "Jirtas" WHERE `ID` = 1200;
UPDATE `mob_db` SET `kName` = "Rybio", `iName` = "Rybio" WHERE `ID` = 1201;
UPDATE `mob_db` SET `kName` = "Fendark", `iName` = "Fendark" WHERE `ID` = 1202;
UPDATE `mob_db` SET `kName` = "Mysteltainn", `iName` = "Mysteltainn" WHERE `ID` = 1203;
UPDATE `mob_db` SET `kName` = "Tirfing", `iName` = "Tirfing" WHERE `ID` = 1204;
UPDATE `mob_db` SET `kName` = "Executor", `iName` = "Executor" WHERE `ID` = 1205;
UPDATE `mob_db` SET `kName` = "Anolian", `iName` = "Anolian" WHERE `ID` = 1206;
UPDATE `mob_db` SET `kName` = "Sting", `iName` = "Sting" WHERE `ID` = 1207;
UPDATE `mob_db` SET `kName` = "Andarilho", `iName` = "Andarilho" WHERE `ID` = 1208;
UPDATE `mob_db` SET `kName` = "Cãibra", `iName` = "Cãibra" WHERE `ID` = 1209;
UPDATE `mob_db` SET `kName` = "Escaravelho", `iName` = "Escaravelho" WHERE `ID` = 1211;
UPDATE `mob_db` SET `kName` = "Mão de Ferro", `iName` = "Mão de Ferro" WHERE `ID` = 1212;
UPDATE `mob_db` SET `kName` = "Grande Orc", `iName` = "Grande Orc" WHERE `ID` = 1213;
UPDATE `mob_db` SET `kName` = "Choco", `iName` = "Choco" WHERE `ID` = 1214;
UPDATE `mob_db` SET `kName` = "Talo de Verme", `iName` = "Talo de Verme" WHERE `ID` = 1215;
UPDATE `mob_db` SET `kName` = "Penomena", `iName` = "Penomena" WHERE `ID` = 1216;
UPDATE `mob_db` SET `kName` = "Cavaleiro do Abismo", `iName` = "Cavaleiro do Abismo" WHERE `ID` = 1219;
UPDATE `mob_db` SET `kName` = "Lobo do Deserto", `iName` = "Lobo do Deserto" WHERE `ID` = 1220;
UPDATE `mob_db` SET `kName` = "Selvagem", `iName` = "Selvagem" WHERE `ID` = 1221;
UPDATE `mob_db` SET `kName` = "Fabre", `iName` = "Fabre" WHERE `ID` = 1229;
UPDATE `mob_db` SET `kName` = "Pupa", `iName` = "Pupa" WHERE `ID` = 1230;
UPDATE `mob_db` SET `kName` = "Creamy", `iName` = "Creamy" WHERE `ID` = 1231;
UPDATE `mob_db` SET `kName` = "Ovo de Peco Peco", `iName` = "Ovo de Peco Peco" WHERE `ID` = 1232;
UPDATE `mob_db` SET `kName` = "Yoyo", `iName` = "Yoyo" WHERE `ID` = 1234;
UPDATE `mob_db` SET `kName` = "Orc Fumante", `iName` = "Orc Fumante" WHERE `ID` = 1235;
UPDATE `mob_db` SET `kName` = "Ovo de Andre", `iName` = "Ovo de Andre" WHERE `ID` = 1236;
UPDATE `mob_db` SET `kName` = "Andre", `iName` = "Andre" WHERE `ID` = 1237;
UPDATE `mob_db` SET `kName` = "Piere", `iName` = "Piere" WHERE `ID` = 1238;
UPDATE `mob_db` SET `kName` = "Deniro", `iName` = "Deniro" WHERE `ID` = 1239;
UPDATE `mob_db` SET `kName` = "Picky", `iName` = "Picky" WHERE `ID` = 1240;
UPDATE `mob_db` SET `kName` = "Picky com Casca", `iName` = "Picky com Casca" WHERE `ID` = 1241;
UPDATE `mob_db` SET `kName` = "Marin", `iName` = "Marin" WHERE `ID` = 1242;
UPDATE `mob_db` SET `kName` = "Sasquatch", `iName` = "Sasquatch" WHERE `ID` = 1243;
UPDATE `mob_db` SET `kName` = "Jakk Natalino", `iName` = "Jakk Natalino" WHERE `ID` = 1244;
UPDATE `mob_db` SET `kName` = "Goblin Natalino", `iName` = "Goblin Natalino" WHERE `ID` = 1245;
UPDATE `mob_db` SET `kName` = "Cookie Natalino", `iName` = "Cookie Natalino" WHERE `ID` = 1246;
UPDATE `mob_db` SET `kName` = "Antonio", `iName` = "Antonio" WHERE `ID` = 1247;
UPDATE `mob_db` SET `kName` = "Soldadinho de Chumbo", `iName` = "Soldadinho de Chumbo" WHERE `ID` = 1248;
UPDATE `mob_db` SET `kName` = "Presente", `iName` = "Presente" WHERE `ID` = 1249;
UPDATE `mob_db` SET `kName` = "Chepet", `iName` = "Chepet" WHERE `ID` = 1250;
UPDATE `mob_db` SET `kName` = "Cavaleiro da Tempestade", `iName` = "Cavaleiro da Tempestade" WHERE `ID` = 1251;
UPDATE `mob_db` SET `kName` = "Hatii", `iName` = "Hatii" WHERE `ID` = 1252;
UPDATE `mob_db` SET `kName` = "Gárgula", `iName` = "Gárgula" WHERE `ID` = 1253;
UPDATE `mob_db` SET `kName` = "Raggler", `iName` = "Raggler" WHERE `ID` = 1254;
UPDATE `mob_db` SET `kName` = "Nereida", `iName` = "Nereida" WHERE `ID` = 1255;
UPDATE `mob_db` SET `kName` = "Peste", `iName` = "Peste" WHERE `ID` = 1256;
UPDATE `mob_db` SET `kName` = "Injustiçado", `iName` = "Injustiçado" WHERE `ID` = 1257;
UPDATE `mob_db` SET `kName` = "Goblin Arqueiro", `iName` = "Goblin Arqueiro" WHERE `ID` = 1258;
UPDATE `mob_db` SET `kName` = "Grifo", `iName` = "Grifo" WHERE `ID` = 1259;
UPDATE `mob_db` SET `kName` = "Moldura Maldita", `iName` = "Moldura Maldita" WHERE `ID` = 1260;
UPDATE `mob_db` SET `kName` = "Rosa Selvagem", `iName` = "Rosa Selvagem" WHERE `ID` = 1261;
UPDATE `mob_db` SET `kName` = "Dragão Mutante", `iName` = "Dragão Mutante" WHERE `ID` = 1262;
UPDATE `mob_db` SET `kName` = "Xamã do Vento", `iName` = "Xamã do Vento" WHERE `ID` = 1263;
UPDATE `mob_db` SET `kName` = "Tritão", `iName` = "Tritão" WHERE `ID` = 1264;
UPDATE `mob_db` SET `kName` = "Cookie", `iName` = "Cookie" WHERE `ID` = 1265;
UPDATE `mob_db` SET `kName` = "Estrela do Mar", `iName` = "Estrela do Mar" WHERE `ID` = 1266;
UPDATE `mob_db` SET `kName` = "Carat", `iName` = "Carat" WHERE `ID` = 1267;
UPDATE `mob_db` SET `kName` = "Cavaleiro Sanguinário", `iName` = "Cavaleiro Sanguinário" WHERE `ID` = 1268;
UPDATE `mob_db` SET `kName` = "Relógio", `iName` = "Relógio" WHERE `ID` = 1269;
UPDATE `mob_db` SET `kName` = "Gerente", `iName` = "Gerente" WHERE `ID` = 1270;
UPDATE `mob_db` SET `kName` = "Crocodilo", `iName` = "Crocodilo" WHERE `ID` = 1271;
UPDATE `mob_db` SET `kName` = "Senhor das Trevas", `iName` = "Senhor das Trevas" WHERE `ID` = 1272;
UPDATE `mob_db` SET `kName` = "Senhora Orc", `iName` = "Senhora Orc" WHERE `ID` = 1273;
UPDATE `mob_db` SET `kName` = "Megalith", `iName` = "Megalith" WHERE `ID` = 1274;
UPDATE `mob_db` SET `kName` = "Alice", `iName` = "Alice" WHERE `ID` = 1275;
UPDATE `mob_db` SET `kName` = "Raydric Arqueiro", `iName` = "Raydric Arqueiro" WHERE `ID` = 1276;
UPDATE `mob_db` SET `kName` = "Guardião da Floresta", `iName` = "Guardião da Floresta" WHERE `ID` = 1277;
UPDATE `mob_db` SET `kName` = "Golem Estalactitico", `iName` = "Golem Estalactitico" WHERE `ID` = 1278;
UPDATE `mob_db` SET `kName` = "Trilobita", `iName` = "Trilobita" WHERE `ID` = 1279;
UPDATE `mob_db` SET `kName` = "Goblin a Vapor", `iName` = "Goblin a Vapor" WHERE `ID` = 1280;
UPDATE `mob_db` SET `kName` = "Verme Sábio", `iName` = "Verme Sábio" WHERE `ID` = 1281;
UPDATE `mob_db` SET `kName` = "Cobold Arqueiro", `iName` = "Cobold Arqueiro" WHERE `ID` = 1282;
UPDATE `mob_db` SET `kName` = "Quimera", `iName` = "Quimera" WHERE `ID` = 1283;
UPDATE `mob_db` SET `kName` = "Guardião Arqueiro", `iName` = "Guardião Arqueiro" WHERE `ID` = 1285;
UPDATE `mob_db` SET `kName` = "Guardião Cavaleiro", `iName` = "Guardião Cavaleiro" WHERE `ID` = 1286;
UPDATE `mob_db` SET `kName` = "Guardião Soldado", `iName` = "Guardião Soldado" WHERE `ID` = 1287;
UPDATE `mob_db` SET `kName` = "Emperium", `iName` = "Emperium" WHERE `ID` = 1288;
UPDATE `mob_db` SET `kName` = "Maya Macho", `iName` = "Maya Macho" WHERE `ID` = 1289;
UPDATE `mob_db` SET `kName` = "Esqueleto General", `iName` = "Esqueleto General" WHERE `ID` = 1290;
UPDATE `mob_db` SET `kName` = "Aparição", `iName` = "Aparição" WHERE `ID` = 1291;
UPDATE `mob_db` SET `kName` = "Diabinho", `iName` = "Diabinho" WHERE `ID` = 1292;
UPDATE `mob_db` SET `kName` = "Creamy Ameaçador", `iName` = "Creamy Ameaçador" WHERE `ID` = 1293;
UPDATE `mob_db` SET `kName` = "Mantis Assassino", `iName` = "Mantis Assassino" WHERE `ID` = 1294;
UPDATE `mob_db` SET `kName` = "Barão Coruja", `iName` = "Barão Coruja" WHERE `ID` = 1295;
UPDATE `mob_db` SET `kName` = "Líder Cobold", `iName` = "Líder Cobold" WHERE `ID` = 1296;
UPDATE `mob_db` SET `kName` = "Múmia Anciã", `iName` = "Múmia Anciã" WHERE `ID` = 1297;
UPDATE `mob_db` SET `kName` = "Zumbi Mestre", `iName` = "Zumbi Mestre" WHERE `ID` = 1298;
UPDATE `mob_db` SET `kName` = "Líder Goblin", `iName` = "Líder Goblin" WHERE `ID` = 1299;
UPDATE `mob_db` SET `kName` = "Lagarta", `iName` = "Lagarta" WHERE `ID` = 1300;
UPDATE `mob_db` SET `kName` = "Am Mut", `iName` = "Am Mut" WHERE `ID` = 1301;
UPDATE `mob_db` SET `kName` = "Ilusão das Trevas", `iName` = "Ilusão das Trevas" WHERE `ID` = 1302;
UPDATE `mob_db` SET `kName` = "Zangão Gigante", `iName` = "Zangão Gigante" WHERE `ID` = 1303;
UPDATE `mob_db` SET `kName` = "Aranha Gigante", `iName` = "Aranha Gigante" WHERE `ID` = 1304;
UPDATE `mob_db` SET `kName` = "Verme Ancião", `iName` = "Verme Ancião" WHERE `ID` = 1305;
UPDATE `mob_db` SET `kName` = "Leib Olmai", `iName` = "Leib Olmai" WHERE `ID` = 1306;
UPDATE `mob_db` SET `kName` = "Gato de Nove Caudas", `iName` = "Gato de Nove Caudas" WHERE `ID` = 1307;
UPDATE `mob_db` SET `kName` = "Panzer Goblin", `iName` = "Panzer Goblin" WHERE `ID` = 1308;
UPDATE `mob_db` SET `kName` = "Gajomart", `iName` = "Gajomart" WHERE `ID` = 1309;
UPDATE `mob_db` SET `kName` = "Majoruros", `iName` = "Majoruros" WHERE `ID` = 1310;
UPDATE `mob_db` SET `kName` = "Gullinbursti", `iName` = "Gullinbursti" WHERE `ID` = 1311;
UPDATE `mob_db` SET `kName` = "General Tartaruga", `iName` = "General Tartaruga" WHERE `ID` = 1312;
UPDATE `mob_db` SET `kName` = "Yakuza", `iName` = "Yakuza" WHERE `ID` = 1313;
UPDATE `mob_db` SET `kName` = "Batedor", `iName` = "Batedor" WHERE `ID` = 1314;
UPDATE `mob_db` SET `kName` = "Agressor", `iName` = "Agressor" WHERE `ID` = 1315;
UPDATE `mob_db` SET `kName` = "Soldado", `iName` = "Soldado" WHERE `ID` = 1316;
UPDATE `mob_db` SET `kName` = "Foca", `iName` = "Foca" WHERE `ID` = 1317;
UPDATE `mob_db` SET `kName` = "Aquecedor", `iName` = "Aquecedor" WHERE `ID` = 1318;
UPDATE `mob_db` SET `kName` = "Congelador", `iName` = "Congelador" WHERE `ID` = 1319;
UPDATE `mob_db` SET `kName` = "Duque Coruja", `iName` = "Duque Coruja" WHERE `ID` = 1320;
UPDATE `mob_db` SET `kName` = "Lavadeira", `iName` = "Lavadeira" WHERE `ID` = 1321;
UPDATE `mob_db` SET `kName` = "Coelho", `iName` = "Coelho" WHERE `ID` = 1322;
UPDATE `mob_db` SET `kName` = "Lontra", `iName` = "Lontra" WHERE `ID` = 1323;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1324;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1325;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1326;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1327;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1328;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1329;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1330;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1331;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1332;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1333;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1334;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1335;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1336;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1337;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1338;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1339;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1340;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1341;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1342;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1343;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1344;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1345;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1346;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1347;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1348;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1349;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1350;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1351;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1352;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1353;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1354;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1355;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1356;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1357;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1358;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1359;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1360;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1361;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1362;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1363;
UPDATE `mob_db` SET `kName` = "Agressor", `iName` = "Agressor" WHERE `ID` = 1364;
UPDATE `mob_db` SET `kName` = "Apocalipse", `iName` = "Apocalipse" WHERE `ID` = 1365;
UPDATE `mob_db` SET `kName` = "Golem de Lava", `iName` = "Golem de Lava" WHERE `ID` = 1366;
UPDATE `mob_db` SET `kName` = "Labareda", `iName` = "Labareda" WHERE `ID` = 1367;
UPDATE `mob_db` SET `kName` = "Planta Carnívora", `iName` = "Planta Carnívora" WHERE `ID` = 1368;
UPDATE `mob_db` SET `kName` = "Grand Peco", `iName` = "Grand Peco" WHERE `ID` = 1369;
UPDATE `mob_db` SET `kName` = "Succubus", `iName` = "Succubus" WHERE `ID` = 1370;
UPDATE `mob_db` SET `kName` = "Anjo Fajuto", `iName` = "Anjo Fajuto" WHERE `ID` = 1371;
UPDATE `mob_db` SET `kName` = "Bode", `iName` = "Bode" WHERE `ID` = 1372;
UPDATE `mob_db` SET `kName` = "Senhor dos Mortos", `iName` = "Senhor dos Mortos" WHERE `ID` = 1373;
UPDATE `mob_db` SET `kName` = "Incubus", `iName` = "Incubus" WHERE `ID` = 1374;
UPDATE `mob_db` SET `kName` = "Papel", `iName` = "Papel" WHERE `ID` = 1375;
UPDATE `mob_db` SET `kName` = "Harpia", `iName` = "Harpia" WHERE `ID` = 1376;
UPDATE `mob_db` SET `kName` = "Ancião", `iName` = "Ancião" WHERE `ID` = 1377;
UPDATE `mob_db` SET `kName` = "Pungus", `iName` = "Pungus" WHERE `ID` = 1378;
UPDATE `mob_db` SET `kName` = "Pesadelo Sombrio", `iName` = "Pesadelo Sombrio" WHERE `ID` = 1379;
UPDATE `mob_db` SET `kName` = "Furador", `iName` = "Furador" WHERE `ID` = 1380;
UPDATE `mob_db` SET `kName` = "Grizzly", `iName` = "Grizzly" WHERE `ID` = 1381;
UPDATE `mob_db` SET `kName` = "Diabólico", `iName` = "Diabólico" WHERE `ID` = 1382;
UPDATE `mob_db` SET `kName` = "Estrondo", `iName` = "Estrondo" WHERE `ID` = 1383;
UPDATE `mob_db` SET `kName` = "Exterminador", `iName` = "Exterminador" WHERE `ID` = 1384;
UPDATE `mob_db` SET `kName` = "Deletério", `iName` = "Deletério" WHERE `ID` = 1385;
UPDATE `mob_db` SET `kName` = "Rochoso", `iName` = "Rochoso" WHERE `ID` = 1386;
UPDATE `mob_db` SET `kName` = "Ferrão", `iName` = "Ferrão" WHERE `ID` = 1387;
UPDATE `mob_db` SET `kName` = "ArchAngeling", `iName` = "ArchAngeling" WHERE `ID` = 1388;
UPDATE `mob_db` SET `kName` = "Drácula", `iName` = "Drácula" WHERE `ID` = 1389;
UPDATE `mob_db` SET `kName` = "Violi", `iName` = "Violi" WHERE `ID` = 1390;
UPDATE `mob_db` SET `kName` = "Pingu", `iName` = "Pingu" WHERE `ID` = 1391;
UPDATE `mob_db` SET `kName` = "Giro-Goblin", `iName` = "Giro-Goblin" WHERE `ID` = 1392;
UPDATE `mob_db` SET `kName` = "Múmia", `iName` = "Múmia" WHERE `ID` = 1393;
UPDATE `mob_db` SET `kName` = "Zumbi", `iName` = "Zumbi" WHERE `ID` = 1394;
UPDATE `mob_db` SET `kName` = "Cristal de Vento", `iName` = "Cristal de Vento" WHERE `ID` = 1395;
UPDATE `mob_db` SET `kName` = "Cristal de Terra", `iName` = "Cristal de Terra" WHERE `ID` = 1396;
UPDATE `mob_db` SET `kName` = "Cristal de Fogo", `iName` = "Cristal de Fogo" WHERE `ID` = 1397;
UPDATE `mob_db` SET `kName` = "Cristal de Água", `iName` = "Cristal de Água" WHERE `ID` = 1398;
UPDATE `mob_db` SET `kName` = "Bafomé", `iName` = "Bafomé" WHERE `ID` = 1399;
UPDATE `mob_db` SET `kName` = "Karakasa", `iName` = "Karakasa" WHERE `ID` = 1400;
UPDATE `mob_db` SET `kName` = "Shinobi", `iName` = "Shinobi" WHERE `ID` = 1401;
UPDATE `mob_db` SET `kName` = "Sapo Venenoso", `iName` = "Sapo Venenoso" WHERE `ID` = 1402;
UPDATE `mob_db` SET `kName` = "Soldado Atirador", `iName` = "Soldado Atirador" WHERE `ID` = 1403;
UPDATE `mob_db` SET `kName` = "Boneco de Miyabi", `iName` = "Boneco de Miyabi" WHERE `ID` = 1404;
UPDATE `mob_db` SET `kName` = "Tengu", `iName` = "Tengu" WHERE `ID` = 1405;
UPDATE `mob_db` SET `kName` = "Kapha", `iName` = "Kapha" WHERE `ID` = 1406;
UPDATE `mob_db` SET `kName` = "Borboleta Sangrenta", `iName` = "Borboleta Sangrenta" WHERE `ID` = 1408;
UPDATE `mob_db` SET `kName` = "Pirralho", `iName` = "Pirralho" WHERE `ID` = 1409;
UPDATE `mob_db` SET `kName` = "Pessegueira Encantada", `iName` = "Pessegueira Encantada" WHERE `ID` = 1410;
UPDATE `mob_db` SET `kName` = "Ermitão Maligno", `iName` = "Ermitão Maligno" WHERE `ID` = 1412;
UPDATE `mob_db` SET `kName` = "Ermitão Selvagem", `iName` = "Ermitão Selvagem" WHERE `ID` = 1413;
UPDATE `mob_db` SET `kName` = "Filhote de Leopardo", `iName` = "Filhote de Leopardo" WHERE `ID` = 1415;
UPDATE `mob_db` SET `kName` = "Ninfa Perversa", `iName` = "Ninfa Perversa" WHERE `ID` = 1416;
UPDATE `mob_db` SET `kName` = "Zipper", `iName` = "Zipper" WHERE `ID` = 1417;
UPDATE `mob_db` SET `kName` = "Serpente Suprema", `iName` = "Serpente Suprema" WHERE `ID` = 1418;
UPDATE `mob_db` SET `kName` = "Familiar", `iName` = "Familiar" WHERE `ID` = 1419;
UPDATE `mob_db` SET `kName` = "Esqueleto Arqueiro", `iName` = "Esqueleto Arqueiro" WHERE `ID` = 1420;
UPDATE `mob_db` SET `kName` = "Isis", `iName` = "Isis" WHERE `ID` = 1421;
UPDATE `mob_db` SET `kName` = "Mosca Caçadora", `iName` = "Mosca Caçadora" WHERE `ID` = 1422;
UPDATE `mob_db` SET `kName` = "Carniçal", `iName` = "Carniçal" WHERE `ID` = 1423;
UPDATE `mob_db` SET `kName` = "Sorrateiro", `iName` = "Sorrateiro" WHERE `ID` = 1424;
UPDATE `mob_db` SET `kName` = "Obeaune", `iName` = "Obeaune" WHERE `ID` = 1425;
UPDATE `mob_db` SET `kName` = "Cavalo-Marinho", `iName` = "Cavalo-Marinho" WHERE `ID` = 1426;
UPDATE `mob_db` SET `kName` = "Pesadelo", `iName` = "Pesadelo" WHERE `ID` = 1427;
UPDATE `mob_db` SET `kName` = "Esporo Venenoso", `iName` = "Esporo Venenoso" WHERE `ID` = 1428;
UPDATE `mob_db` SET `kName` = "Argiope", `iName` = "Argiope" WHERE `ID` = 1429;
UPDATE `mob_db` SET `kName` = "Argos", `iName` = "Argos" WHERE `ID` = 1430;
UPDATE `mob_db` SET `kName` = "Bafomé Jr.", `iName` = "Bafomé Jr." WHERE `ID` = 1431;
UPDATE `mob_db` SET `kName` = "Lobo do Deserto", `iName` = "Lobo do Deserto" WHERE `ID` = 1432;
UPDATE `mob_db` SET `kName` = "Deviruchi", `iName` = "Deviruchi" WHERE `ID` = 1433;
UPDATE `mob_db` SET `kName` = "Drainliar", `iName` = "Drainliar" WHERE `ID` = 1434;
UPDATE `mob_db` SET `kName` = "Druida Maligno", `iName` = "Druida Maligno" WHERE `ID` = 1435;
UPDATE `mob_db` SET `kName` = "Jakk", `iName` = "Jakk" WHERE `ID` = 1436;
UPDATE `mob_db` SET `kName` = "Joker", `iName` = "Joker" WHERE `ID` = 1437;
UPDATE `mob_db` SET `kName` = "Khalitzburg", `iName` = "Khalitzburg" WHERE `ID` = 1438;
UPDATE `mob_db` SET `kName` = "Grande Orc", `iName` = "Grande Orc" WHERE `ID` = 1439;
UPDATE `mob_db` SET `kName` = "Talo de Verme", `iName` = "Talo de Verme" WHERE `ID` = 1440;
UPDATE `mob_db` SET `kName` = "Penomena", `iName` = "Penomena" WHERE `ID` = 1441;
UPDATE `mob_db` SET `kName` = "Sasquatch", `iName` = "Sasquatch" WHERE `ID` = 1442;
UPDATE `mob_db` SET `kName` = "Soldadinho de Chumbo", `iName` = "Soldadinho de Chumbo" WHERE `ID` = 1443;
UPDATE `mob_db` SET `kName` = "Chepet", `iName` = "Chepet" WHERE `ID` = 1444;
UPDATE `mob_db` SET `kName` = "Raggler", `iName` = "Raggler" WHERE `ID` = 1445;
UPDATE `mob_db` SET `kName` = "Injustiçado", `iName` = "Injustiçado" WHERE `ID` = 1446;
UPDATE `mob_db` SET `kName` = "Grifo", `iName` = "Grifo" WHERE `ID` = 1447;
UPDATE `mob_db` SET `kName` = "Moldura Maldita", `iName` = "Moldura Maldita" WHERE `ID` = 1448;
UPDATE `mob_db` SET `kName` = "Dragão Mutante", `iName` = "Dragão Mutante" WHERE `ID` = 1449;
UPDATE `mob_db` SET `kName` = "Xamã do Vento", `iName` = "Xamã do Vento" WHERE `ID` = 1450;
UPDATE `mob_db` SET `kName` = "Tritão", `iName` = "Tritão" WHERE `ID` = 1451;
UPDATE `mob_db` SET `kName` = "Senhora Orc", `iName` = "Senhora Orc" WHERE `ID` = 1452;
UPDATE `mob_db` SET `kName` = "Raydric Arqueiro", `iName` = "Raydric Arqueiro" WHERE `ID` = 1453;
UPDATE `mob_db` SET `kName` = "Trilobita", `iName` = "Trilobita" WHERE `ID` = 1454;
UPDATE `mob_db` SET `kName` = "Cobold Arqueiro", `iName` = "Cobold Arqueiro" WHERE `ID` = 1455;
UPDATE `mob_db` SET `kName` = "Quimera", `iName` = "Quimera" WHERE `ID` = 1456;
UPDATE `mob_db` SET `kName` = "Mantis", `iName` = "Mantis" WHERE `ID` = 1457;
UPDATE `mob_db` SET `kName` = "Marduk", `iName` = "Marduk" WHERE `ID` = 1458;
UPDATE `mob_db` SET `kName` = "Marionete", `iName` = "Marionete" WHERE `ID` = 1459;
UPDATE `mob_db` SET `kName` = "Matyr", `iName` = "Matyr" WHERE `ID` = 1460;
UPDATE `mob_db` SET `kName` = "Minorous", `iName` = "Minorous" WHERE `ID` = 1461;
UPDATE `mob_db` SET `kName` = "Orc Esqueleto", `iName` = "Orc Esqueleto" WHERE `ID` = 1462;
UPDATE `mob_db` SET `kName` = "Orc Zumbi", `iName` = "Orc Zumbi" WHERE `ID` = 1463;
UPDATE `mob_db` SET `kName` = "Pasana", `iName` = "Pasana" WHERE `ID` = 1464;
UPDATE `mob_db` SET `kName` = "Petite", `iName` = "Petite" WHERE `ID` = 1465;
UPDATE `mob_db` SET `kName` = "Petite Voador", `iName` = "Petite Voador" WHERE `ID` = 1466;
UPDATE `mob_db` SET `kName` = "Raydric", `iName` = "Raydric" WHERE `ID` = 1467;
UPDATE `mob_db` SET `kName` = "Réquiem", `iName` = "Réquiem" WHERE `ID` = 1468;
UPDATE `mob_db` SET `kName` = "Esqueleto Operário", `iName` = "Esqueleto Operário" WHERE `ID` = 1469;
UPDATE `mob_db` SET `kName` = "Zerom", `iName` = "Zerom" WHERE `ID` = 1470;
UPDATE `mob_db` SET `kName` = "Nove Caudas", `iName` = "Nove Caudas" WHERE `ID` = 1471;
UPDATE `mob_db` SET `kName` = "Bongun", `iName` = "Bongun" WHERE `ID` = 1472;
UPDATE `mob_db` SET `kName` = "Orc Arqueiro", `iName` = "Orc Arqueiro" WHERE `ID` = 1473;
UPDATE `mob_db` SET `kName` = "Mímico", `iName` = "Mímico" WHERE `ID` = 1474;
UPDATE `mob_db` SET `kName` = "Alma Penada", `iName` = "Alma Penada" WHERE `ID` = 1475;
UPDATE `mob_db` SET `kName` = "Alarme", `iName` = "Alarme" WHERE `ID` = 1476;
UPDATE `mob_db` SET `kName` = "Arclouse", `iName` = "Arclouse" WHERE `ID` = 1477;
UPDATE `mob_db` SET `kName` = "Rideword", `iName` = "Rideword" WHERE `ID` = 1478;
UPDATE `mob_db` SET `kName` = "Esqueleto Prisioneiro", `iName` = "Esqueleto Prisioneiro" WHERE `ID` = 1479;
UPDATE `mob_db` SET `kName` = "Zumbi Prisioneiro", `iName` = "Zumbi Prisioneiro" WHERE `ID` = 1480;
UPDATE `mob_db` SET `kName` = "Punk", `iName` = "Punk" WHERE `ID` = 1481;
UPDATE `mob_db` SET `kName` = "Jirtas", `iName` = "Jirtas" WHERE `ID` = 1482;
UPDATE `mob_db` SET `kName` = "Rybio", `iName` = "Rybio" WHERE `ID` = 1483;
UPDATE `mob_db` SET `kName` = "Fendark", `iName` = "Fendark" WHERE `ID` = 1484;
UPDATE `mob_db` SET `kName` = "Mysteltainn", `iName` = "Mysteltainn" WHERE `ID` = 1485;
UPDATE `mob_db` SET `kName` = "Tirfing", `iName` = "Tirfing" WHERE `ID` = 1486;
UPDATE `mob_db` SET `kName` = "Executor", `iName` = "Executor" WHERE `ID` = 1487;
UPDATE `mob_db` SET `kName` = "Anolian", `iName` = "Anolian" WHERE `ID` = 1488;
UPDATE `mob_db` SET `kName` = "Sting", `iName` = "Sting" WHERE `ID` = 1489;
UPDATE `mob_db` SET `kName` = "Andarilho", `iName` = "Andarilho" WHERE `ID` = 1490;
UPDATE `mob_db` SET `kName` = "Dokebi", `iName` = "Dokebi" WHERE `ID` = 1491;
UPDATE `mob_db` SET `kName` = "Samurai Encarnado", `iName` = "Samurai Encarnado" WHERE `ID` = 1492;
UPDATE `mob_db` SET `kName` = "Dríade", `iName` = "Dríade" WHERE `ID` = 1493;
UPDATE `mob_db` SET `kName` = "Besouro-Rei", `iName` = "Besouro-Rei" WHERE `ID` = 1494;
UPDATE `mob_db` SET `kName` = "Atirador de Pedras", `iName` = "Atirador de Pedras" WHERE `ID` = 1495;
UPDATE `mob_db` SET `kName` = "Golem de Madeira", `iName` = "Golem de Madeira" WHERE `ID` = 1497;
UPDATE `mob_db` SET `kName` = "Atirador Wootan", `iName` = "Atirador Wootan" WHERE `ID` = 1498;
UPDATE `mob_db` SET `kName` = "Guerreiro Wootan", `iName` = "Guerreiro Wootan" WHERE `ID` = 1499;
UPDATE `mob_db` SET `kName` = "Parasita", `iName` = "Parasita" WHERE `ID` = 1500;
UPDATE `mob_db` SET `kName` = "Pori Pori", `iName` = "Pori Pori" WHERE `ID` = 1502;
UPDATE `mob_db` SET `kName` = "Árvore Maldita", `iName` = "Árvore Maldita" WHERE `ID` = 1503;
UPDATE `mob_db` SET `kName` = "Dullahan", `iName` = "Dullahan" WHERE `ID` = 1504;
UPDATE `mob_db` SET `kName` = "Loli Ruri", `iName` = "Loli Ruri" WHERE `ID` = 1505;
UPDATE `mob_db` SET `kName` = "Mascarado", `iName` = "Mascarado" WHERE `ID` = 1506;
UPDATE `mob_db` SET `kName` = "Serial Killer", `iName` = "Serial Killer" WHERE `ID` = 1507;
UPDATE `mob_db` SET `kName` = "Quve", `iName` = "Quve" WHERE `ID` = 1508;
UPDATE `mob_db` SET `kName` = "Lude", `iName` = "Lude" WHERE `ID` = 1509;
UPDATE `mob_db` SET `kName` = "Poltergeist", `iName` = "Poltergeist" WHERE `ID` = 1510;
UPDATE `mob_db` SET `kName` = "Amon Ra", `iName` = "Amon Ra" WHERE `ID` = 1511;
UPDATE `mob_db` SET `kName` = "Yao Jun", `iName` = "Yao Jun" WHERE `ID` = 1512;
UPDATE `mob_db` SET `kName` = "Mao Guai", `iName` = "Mao Guai" WHERE `ID` = 1513;
UPDATE `mob_db` SET `kName` = "Zhu Po Long", `iName` = "Zhu Po Long" WHERE `ID` = 1514;
UPDATE `mob_db` SET `kName` = "Filhote de Hatii", `iName` = "Filhote de Hatii" WHERE `ID` = 1515;
UPDATE `mob_db` SET `kName` = "Mi Gao", `iName` = "Mi Gao" WHERE `ID` = 1516;
UPDATE `mob_db` SET `kName` = "Jing Guai", `iName` = "Jing Guai" WHERE `ID` = 1517;
UPDATE `mob_db` SET `kName` = "Dama de Branco", `iName` = "Dama de Branco" WHERE `ID` = 1518;
UPDATE `mob_db` SET `kName` = "Chung E", `iName` = "Chung E" WHERE `ID` = 1519;
UPDATE `mob_db` SET `kName` = "Bolinho de Massa", `iName` = "Bolinho de Massa" WHERE `ID` = 1520;
UPDATE `mob_db` SET `kName` = "Alice", `iName` = "Alice" WHERE `ID` = 1521;
UPDATE `mob_db` SET `kName` = "Múmia Anciã", `iName` = "Múmia Anciã" WHERE `ID` = 1522;
UPDATE `mob_db` SET `kName` = "Soldado Atirador", `iName` = "Soldado Atirador" WHERE `ID` = 1523;
UPDATE `mob_db` SET `kName` = "Leopardo Filhote", `iName` = "Leopardo Filhote" WHERE `ID` = 1524;
UPDATE `mob_db` SET `kName` = "Bathory", `iName` = "Bathory" WHERE `ID` = 1525;
UPDATE `mob_db` SET `kName` = "Borboleta Sanguinária", `iName` = "Borboleta Sanguinária" WHERE `ID` = 1526;
UPDATE `mob_db` SET `kName` = "Gerente", `iName` = "Gerente" WHERE `ID` = 1527;
UPDATE `mob_db` SET `kName` = "Relógio", `iName` = "Relógio" WHERE `ID` = 1528;
UPDATE `mob_db` SET `kName` = "Serpente Suprema", `iName` = "Serpente Suprema" WHERE `ID` = 1529;
UPDATE `mob_db` SET `kName` = "Drácula", `iName` = "Drácula" WHERE `ID` = 1530;
UPDATE `mob_db` SET `kName` = "Ermitão Maligno", `iName` = "Ermitão Maligno" WHERE `ID` = 1531;
UPDATE `mob_db` SET `kName` = "Estrondo", `iName` = "Estrondo" WHERE `ID` = 1532;
UPDATE `mob_db` SET `kName` = "Foca", `iName` = "Foca" WHERE `ID` = 1533;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1534;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1535;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1536;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1537;
UPDATE `mob_db` SET `kName` = "Goblin", `iName` = "Goblin" WHERE `ID` = 1538;
UPDATE `mob_db` SET `kName` = "Líder Goblin", `iName` = "Líder Goblin" WHERE `ID` = 1539;
UPDATE `mob_db` SET `kName` = "Golem", `iName` = "Golem" WHERE `ID` = 1540;
UPDATE `mob_db` SET `kName` = "Guardião da Floresta", `iName` = "Guardião da Floresta" WHERE `ID` = 1541;
UPDATE `mob_db` SET `kName` = "Samurai Encarnado", `iName` = "Samurai Encarnado" WHERE `ID` = 1542;
UPDATE `mob_db` SET `kName` = "Kapha", `iName` = "Kapha" WHERE `ID` = 1543;
UPDATE `mob_db` SET `kName` = "Karakasa", `iName` = "Karakasa" WHERE `ID` = 1544;
UPDATE `mob_db` SET `kName` = "Kobold", `iName` = "Kobold" WHERE `ID` = 1545;
UPDATE `mob_db` SET `kName` = "Kobold", `iName` = "Kobold" WHERE `ID` = 1546;
UPDATE `mob_db` SET `kName` = "Kobold", `iName` = "Kobold" WHERE `ID` = 1547;
UPDATE `mob_db` SET `kName` = "Líder Kobold", `iName` = "Líder Kobold" WHERE `ID` = 1548;
UPDATE `mob_db` SET `kName` = "Golem de Lava", `iName` = "Golem de Lava" WHERE `ID` = 1549;
UPDATE `mob_db` SET `kName` = "Pessegueira Encantada", `iName` = "Pessegueira Encantada" WHERE `ID` = 1550;
UPDATE `mob_db` SET `kName` = "Marte", `iName` = "Marte" WHERE `ID` = 1551;
UPDATE `mob_db` SET `kName` = "Boneco de Miyabi", `iName` = "Boneco de Miyabi" WHERE `ID` = 1552;
UPDATE `mob_db` SET `kName` = "Névoa", `iName` = "Névoa" WHERE `ID` = 1553;
UPDATE `mob_db` SET `kName` = "Pesadelo Sombrio", `iName` = "Pesadelo Sombrio" WHERE `ID` = 1554;
UPDATE `mob_db` SET `kName` = "Parasita", `iName` = "Parasita" WHERE `ID` = 1555;
UPDATE `mob_db` SET `kName` = "Sapo Venenoso", `iName` = "Sapo Venenoso" WHERE `ID` = 1556;
UPDATE `mob_db` SET `kName` = "Giro-Goblin", `iName` = "Giro-Goblin" WHERE `ID` = 1557;
UPDATE `mob_db` SET `kName` = "Arenoso", `iName` = "Arenoso" WHERE `ID` = 1558;
UPDATE `mob_db` SET `kName` = "Escorpião", `iName` = "Escorpião" WHERE `ID` = 1559;
UPDATE `mob_db` SET `kName` = "Shinobi", `iName` = "Shinobi" WHERE `ID` = 1560;
UPDATE `mob_db` SET `kName` = "Fumacento", `iName` = "Fumacento" WHERE `ID` = 1561;
UPDATE `mob_db` SET `kName` = "Esqueleto Soldado", `iName` = "Esqueleto Soldado" WHERE `ID` = 1562;
UPDATE `mob_db` SET `kName` = "Tengu", `iName` = "Tengu" WHERE `ID` = 1563;
UPDATE `mob_db` SET `kName` = "Ninfa Perversa", `iName` = "Ninfa Perversa" WHERE `ID` = 1564;
UPDATE `mob_db` SET `kName` = "Ermitão Selvagem", `iName` = "Ermitão Selvagem" WHERE `ID` = 1565;
UPDATE `mob_db` SET `kName` = "Aparição", `iName` = "Aparição" WHERE `ID` = 1566;
UPDATE `mob_db` SET `kName` = "Verme Ancião", `iName` = "Verme Ancião" WHERE `ID` = 1567;
UPDATE `mob_db` SET `kName` = "Angeling", `iName` = "Angeling" WHERE `ID` = 1568;
UPDATE `mob_db` SET `kName` = "Cavaleiro Sanguinário", `iName` = "Cavaleiro Sanguinário" WHERE `ID` = 1569;
UPDATE `mob_db` SET `kName` = "Cãibra", `iName` = "Cãibra" WHERE `ID` = 1570;
UPDATE `mob_db` SET `kName` = "Deviace", `iName` = "Deviace" WHERE `ID` = 1571;
UPDATE `mob_db` SET `kName` = "Drops", `iName` = "Drops" WHERE `ID` = 1572;
UPDATE `mob_db` SET `kName` = "Ancião", `iName` = "Ancião" WHERE `ID` = 1573;
UPDATE `mob_db` SET `kName` = "Salgueiro Ancião", `iName` = "Salgueiro Ancião" WHERE `ID` = 1574;
UPDATE `mob_db` SET `kName` = "Flora", `iName` = "Flora" WHERE `ID` = 1575;
UPDATE `mob_db` SET `kName` = "Ghostring", `iName` = "Ghostring" WHERE `ID` = 1576;
UPDATE `mob_db` SET `kName` = "Goblin Arqueiro", `iName` = "Goblin Arqueiro" WHERE `ID` = 1577;
UPDATE `mob_db` SET `kName` = "Horong", `iName` = "Horong" WHERE `ID` = 1578;
UPDATE `mob_db` SET `kName` = "Hidra", `iName` = "Hidra" WHERE `ID` = 1579;
UPDATE `mob_db` SET `kName` = "Incubus", `iName` = "Incubus" WHERE `ID` = 1580;
UPDATE `mob_db` SET `kName` = "Vocal", `iName` = "Vocal" WHERE `ID` = 1581;
UPDATE `mob_db` SET `kName` = "Deviling", `iName` = "Deviling" WHERE `ID` = 1582;
UPDATE `mob_db` SET `kName` = "Tao Gunka", `iName` = "Tao Gunka" WHERE `ID` = 1583;
UPDATE `mob_db` SET `kName` = "Tamruan", `iName` = "Tamruan" WHERE `ID` = 1584;
UPDATE `mob_db` SET `kName` = "Macaco Mimado", `iName` = "Macaco Mimado" WHERE `ID` = 1585;
UPDATE `mob_db` SET `kName` = "Gato de Folha", `iName` = "Gato de Folha" WHERE `ID` = 1586;
UPDATE `mob_db` SET `kName` = "Kraben", `iName` = "Kraben" WHERE `ID` = 1587;
UPDATE `mob_db` SET `kName` = "Orc Natalino", `iName` = "Orc Natalino" WHERE `ID` = 1588;
UPDATE `mob_db` SET `kName` = "Mandrágora", `iName` = "Mandrágora" WHERE `ID` = 1589;
UPDATE `mob_db` SET `kName` = "Planta Carnívora", `iName` = "Planta Carnívora" WHERE `ID` = 1590;
UPDATE `mob_db` SET `kName` = "Lunático", `iName` = "Lunático" WHERE `ID` = 1591;
UPDATE `mob_db` SET `kName` = "Yakuza", `iName` = "Yakuza" WHERE `ID` = 1592;
UPDATE `mob_db` SET `kName` = "Múmia Anciã", `iName` = "Múmia Anciã" WHERE `ID` = 1593;
UPDATE `mob_db` SET `kName` = "Congelador", `iName` = "Congelador" WHERE `ID` = 1594;
UPDATE `mob_db` SET `kName` = "Marin", `iName` = "Marin" WHERE `ID` = 1595;
UPDATE `mob_db` SET `kName` = "Tamruan", `iName` = "Tamruan" WHERE `ID` = 1596;
UPDATE `mob_db` SET `kName` = "Gárgula", `iName` = "Gárgula" WHERE `ID` = 1597;
UPDATE `mob_db` SET `kName` = "Labareda", `iName` = "Labareda" WHERE `ID` = 1598;
UPDATE `mob_db` SET `kName` = "Cochicho", `iName` = "Cochicho" WHERE `ID` = 1599;
UPDATE `mob_db` SET `kName` = "Aquecedor", `iName` = "Aquecedor" WHERE `ID` = 1600;
UPDATE `mob_db` SET `kName` = "Batedor", `iName` = "Batedor" WHERE `ID` = 1601;
UPDATE `mob_db` SET `kName` = "Soldado", `iName` = "Soldado" WHERE `ID` = 1602;
UPDATE `mob_db` SET `kName` = "Pé Grande", `iName` = "Pé Grande" WHERE `ID` = 1603;
UPDATE `mob_db` SET `kName` = "Zangão Gigante", `iName` = "Zangão Gigante" WHERE `ID` = 1604;
UPDATE `mob_db` SET `kName` = "Ilusão das Trevas", `iName` = "Ilusão das Trevas" WHERE `ID` = 1605;
UPDATE `mob_db` SET `kName` = "Filho de Hatii", `iName` = "Filho de Hatii" WHERE `ID` = 1606;
UPDATE `mob_db` SET `kName` = "Goblin Natalino", `iName` = "Goblin Natalino" WHERE `ID` = 1607;
UPDATE `mob_db` SET `kName` = "Besouro-Ladrão Fêmea", `iName` = "Besouro-Ladrão Fêmea" WHERE `ID` = 1608;
UPDATE `mob_db` SET `kName` = "Zhu Po Long", `iName` = "Zhu Po Long" WHERE `ID` = 1609;
UPDATE `mob_db` SET `kName` = "Munak", `iName` = "Munak" WHERE `ID` = 1610;
UPDATE `mob_db` SET `kName` = "Bongun", `iName` = "Bongun" WHERE `ID` = 1611;
UPDATE `mob_db` SET `kName` = "Yao Jun", `iName` = "Yao Jun" WHERE `ID` = 1612;
UPDATE `mob_db` SET `kName` = "Metaling", `iName` = "Metaling" WHERE `ID` = 1613;
UPDATE `mob_db` SET `kName` = "Mineral", `iName` = "Mineral" WHERE `ID` = 1614;
UPDATE `mob_db` SET `kName` = "Obsidiana", `iName` = "Obsidiana" WHERE `ID` = 1615;
UPDATE `mob_db` SET `kName` = "Mineiros", `iName` = "Mineiros" WHERE `ID` = 1616;
UPDATE `mob_db` SET `kName` = "Fornalha Velha", `iName` = "Fornalha Velha" WHERE `ID` = 1617;
UPDATE `mob_db` SET `kName` = "Ungoliant", `iName` = "Ungoliant" WHERE `ID` = 1618;
UPDATE `mob_db` SET `kName` = "Porcellio", `iName` = "Porcellio" WHERE `ID` = 1619;
UPDATE `mob_db` SET `kName` = "Nuvem Tóxica", `iName` = "Nuvem Tóxica" WHERE `ID` = 1620;
UPDATE `mob_db` SET `kName` = "Nuvem Venenosa", `iName` = "Nuvem Venenosa" WHERE `ID` = 1621;
UPDATE `mob_db` SET `kName` = "Ursinho", `iName` = "Ursinho" WHERE `ID` = 1622;
UPDATE `mob_db` SET `kName` = "RSX-0806", `iName` = "RSX-0806" WHERE `ID` = 1623;
UPDATE `mob_db` SET `kName` = "Fornalha Velha", `iName` = "Fornalha Velha" WHERE `ID` = 1624;
UPDATE `mob_db` SET `kName` = "Porcellio", `iName` = "Porcellio" WHERE `ID` = 1625;
UPDATE `mob_db` SET `kName` = "Espectro de Hellion", `iName` = "Espectro de Hellion" WHERE `ID` = 1626;
UPDATE `mob_db` SET `kName` = "Anopheles", `iName` = "Anopheles" WHERE `ID` = 1627;
UPDATE `mob_db` SET `kName` = "Holden", `iName` = "Holden" WHERE `ID` = 1628;
UPDATE `mob_db` SET `kName` = "Vento da Colina", `iName` = "Vento da Colina" WHERE `ID` = 1629;
UPDATE `mob_db` SET `kName` = "Dama de Branco", `iName` = "Dama de Branco" WHERE `ID` = 1630;
UPDATE `mob_db` SET `kName` = "Donzela Verde", `iName` = "Donzela Verde" WHERE `ID` = 1631;
UPDATE `mob_db` SET `kName` = "Gremlin", `iName` = "Gremlin" WHERE `ID` = 1632;
UPDATE `mob_db` SET `kName` = "Beholder", `iName` = "Beholder" WHERE `ID` = 1633;
UPDATE `mob_db` SET `kName` = "Seyren Windsor", `iName` = "Seyren Windsor" WHERE `ID` = 1634;
UPDATE `mob_db` SET `kName` = "Eremes Guile", `iName` = "Eremes Guile" WHERE `ID` = 1635;
UPDATE `mob_db` SET `kName` = "Howard Alt-Eisen", `iName` = "Howard Alt-Eisen" WHERE `ID` = 1636;
UPDATE `mob_db` SET `kName` = "Margaretha Sorin", `iName` = "Margaretha Sorin" WHERE `ID` = 1637;
UPDATE `mob_db` SET `kName` = "Cecil Damon", `iName` = "Cecil Damon" WHERE `ID` = 1638;
UPDATE `mob_db` SET `kName` = "Kathryne Keyron", `iName` = "Kathryne Keyron" WHERE `ID` = 1639;
UPDATE `mob_db` SET `kName` = "Lorde Seyren", `iName` = "Lorde Seyren" WHERE `ID` = 1640;
UPDATE `mob_db` SET `kName` = "Algoz Eremes", `iName` = "Algoz Eremes" WHERE `ID` = 1641;
UPDATE `mob_db` SET `kName` = "Mestre-Ferreiro Howard", `iName` = "Mestre-Ferreiro Howard" WHERE `ID` = 1642;
UPDATE `mob_db` SET `kName` = "Suma-Sacerdotisa Margaretha", `iName` = "Suma-Sacerdotisa Margaretha" WHERE `ID` = 1643;
UPDATE `mob_db` SET `kName` = "Atiradora de Elite Cecil", `iName` = "Atiradora de Elite Cecil" WHERE `ID` = 1644;
UPDATE `mob_db` SET `kName` = "Arquimaga Kathryne", `iName` = "Arquimaga Kathryne" WHERE `ID` = 1645;
UPDATE `mob_db` SET `kName` = "Lorde Seyren", `iName` = "Lorde Seyren" WHERE `ID` = 1646;
UPDATE `mob_db` SET `kName` = "Algoz Eremes", `iName` = "Algoz Eremes" WHERE `ID` = 1647;
UPDATE `mob_db` SET `kName` = "Mestre-Ferreiro Howard", `iName` = "Mestre-Ferreiro Howard" WHERE `ID` = 1648;
UPDATE `mob_db` SET `kName` = "Suma-Sacerdotiza Magaleta", `iName` = "Suma-Sacerdotiza Magaleta" WHERE `ID` = 1649;
UPDATE `mob_db` SET `kName` = "Atiradora de Elite Cecil", `iName` = "Atiradora de Elite Cecil" WHERE `ID` = 1650;
UPDATE `mob_db` SET `kName` = "Arquimaga Kathryne", `iName` = "Arquimaga Kathryne" WHERE `ID` = 1651;
UPDATE `mob_db` SET `kName` = "Egnigem Cenia", `iName` = "Egnigem Cenia" WHERE `ID` = 1652;
UPDATE `mob_db` SET `kName` = "Wickebine Tres", `iName` = "Wickebine Tres" WHERE `ID` = 1653;
UPDATE `mob_db` SET `kName` = "Armeyer Dinze", `iName` = "Armeyer Dinze" WHERE `ID` = 1654;
UPDATE `mob_db` SET `kName` = "Errende Ebecee", `iName` = "Errende Ebecee" WHERE `ID` = 1655;
UPDATE `mob_db` SET `kName` = "Kavach Icarus", `iName` = "Kavach Icarus" WHERE `ID` = 1656;
UPDATE `mob_db` SET `kName` = "Laurell Weinder", `iName` = "Laurell Weinder" WHERE `ID` = 1657;
UPDATE `mob_db` SET `kName` = "Egnigem Cenia", `iName` = "Egnigem Cenia" WHERE `ID` = 1658;
UPDATE `mob_db` SET `kName` = "Wickebine Tres", `iName` = "Wickebine Tres" WHERE `ID` = 1659;
UPDATE `mob_db` SET `kName` = "Armeyer Dinze", `iName` = "Armeyer Dinze" WHERE `ID` = 1660;
UPDATE `mob_db` SET `kName` = "Errende Ebecee", `iName` = "Errende Ebecee" WHERE `ID` = 1661;
UPDATE `mob_db` SET `kName` = "Kavach Icarus", `iName` = "Kavach Icarus" WHERE `ID` = 1662;
UPDATE `mob_db` SET `kName` = "Laurell Weinder", `iName` = "Laurell Weinder" WHERE `ID` = 1663;
UPDATE `mob_db` SET `kName` = "Canhão de Fóton", `iName` = "Canhão de Fóton" WHERE `ID` = 1664;
UPDATE `mob_db` SET `kName` = "Canhão de Fóton", `iName` = "Canhão de Fóton" WHERE `ID` = 1665;
UPDATE `mob_db` SET `kName` = "Canhão de Fóton", `iName` = "Canhão de Fóton" WHERE `ID` = 1666;
UPDATE `mob_db` SET `kName` = "Canhão de Fóton", `iName` = "Canhão de Fóton" WHERE `ID` = 1667;
UPDATE `mob_db` SET `kName` = "Archdam", `iName` = "Archdam" WHERE `ID` = 1668;
UPDATE `mob_db` SET `kName` = "Dimik", `iName` = "Dimik" WHERE `ID` = 1669;
UPDATE `mob_db` SET `kName` = "Dimik", `iName` = "Dimik" WHERE `ID` = 1670;
UPDATE `mob_db` SET `kName` = "Dimik", `iName` = "Dimik" WHERE `ID` = 1671;
UPDATE `mob_db` SET `kName` = "Dimik", `iName` = "Dimik" WHERE `ID` = 1672;
UPDATE `mob_db` SET `kName` = "Dimik", `iName` = "Dimik" WHERE `ID` = 1673;
UPDATE `mob_db` SET `kName` = "Monemus", `iName` = "Monemus" WHERE `ID` = 1674;
UPDATE `mob_db` SET `kName` = "Venatu", `iName` = "Venatu" WHERE `ID` = 1675;
UPDATE `mob_db` SET `kName` = "Venatu", `iName` = "Venatu" WHERE `ID` = 1676;
UPDATE `mob_db` SET `kName` = "Venatu", `iName` = "Venatu" WHERE `ID` = 1677;
UPDATE `mob_db` SET `kName` = "Venatu", `iName` = "Venatu" WHERE `ID` = 1678;
UPDATE `mob_db` SET `kName` = "Venatu", `iName` = "Venatu" WHERE `ID` = 1679;
UPDATE `mob_db` SET `kName` = "Vento da Colina", `iName` = "Vento da Colina" WHERE `ID` = 1680;
UPDATE `mob_db` SET `kName` = "Gemini-S58", `iName` = "Gemini-S58" WHERE `ID` = 1681;
UPDATE `mob_db` SET `kName` = "Exterminador", `iName` = "Exterminador" WHERE `ID` = 1682;
UPDATE `mob_db` SET `kName` = "Canhão de Fóton", `iName` = "Canhão de Fóton" WHERE `ID` = 1683;
UPDATE `mob_db` SET `kName` = "Archdam", `iName` = "Archdam" WHERE `ID` = 1684;
UPDATE `mob_db` SET `kName` = "Vesper", `iName` = "Vesper" WHERE `ID` = 1685;
UPDATE `mob_db` SET `kName` = "Filhote de Orc", `iName` = "Filhote de Orc" WHERE `ID` = 1686;
UPDATE `mob_db` SET `kName` = "Grove", `iName` = "Grove" WHERE `ID` = 1687;
UPDATE `mob_db` SET `kName` = "Lady Tanee", `iName` = "Lady Tanee" WHERE `ID` = 1688;
UPDATE `mob_db` SET `kName` = "Dama de Branco", `iName` = "Dama de Branco" WHERE `ID` = 1689;
UPDATE `mob_db` SET `kName` = "Coelho", `iName` = "Coelho" WHERE `ID` = 1690;
UPDATE `mob_db` SET `kName` = "Kraben", `iName` = "Kraben" WHERE `ID` = 1691;
UPDATE `mob_db` SET `kName` = "Breeze", `iName` = "Breeze" WHERE `ID` = 1692;
UPDATE `mob_db` SET `kName` = "Plasma", `iName` = "Plasma" WHERE `ID` = 1693;
UPDATE `mob_db` SET `kName` = "Plasma", `iName` = "Plasma" WHERE `ID` = 1694;
UPDATE `mob_db` SET `kName` = "Plasma", `iName` = "Plasma" WHERE `ID` = 1695;
UPDATE `mob_db` SET `kName` = "Plasma", `iName` = "Plasma" WHERE `ID` = 1696;
UPDATE `mob_db` SET `kName` = "Plasma", `iName` = "Plasma" WHERE `ID` = 1697;
UPDATE `mob_db` SET `kName` = "Palavra Morta", `iName` = "Palavra Morta" WHERE `ID` = 1698;
UPDATE `mob_db` SET `kName` = "Mímico Antigo", `iName` = "Mímico Antigo" WHERE `ID` = 1699;
UPDATE `mob_db` SET `kName` = "Dama de Guarda", `iName` = "Dama de Guarda" WHERE `ID` = 1700;
UPDATE `mob_db` SET `kName` = "Senhora do Abrigo", `iName` = "Senhora do Abrigo" WHERE `ID` = 1701;
UPDATE `mob_db` SET `kName` = "Baronesa da Retribuição", `iName` = "Baronesa da Retribuição" WHERE `ID` = 1702;
UPDATE `mob_db` SET `kName` = "Lady Solace", `iName` = "Lady Solace" WHERE `ID` = 1703;
UPDATE `mob_db` SET `kName` = "Odium de Thanatos", `iName` = "Odium de Thanatos" WHERE `ID` = 1704;
UPDATE `mob_db` SET `kName` = "Despero de Thanatos", `iName` = "Despero de Thanatos" WHERE `ID` = 1705;
UPDATE `mob_db` SET `kName` = "Maero de Thanatos", `iName` = "Maero de Thanatos" WHERE `ID` = 1706;
UPDATE `mob_db` SET `kName` = "Pesar de Thanatos", `iName` = "Pesar de Thanatos" WHERE `ID` = 1707;
UPDATE `mob_db` SET `kName` = "Memória de Thanatos", `iName` = "Memória de Thanatos" WHERE `ID` = 1708;
UPDATE `mob_db` SET `kName` = "Odium de Thanatos", `iName` = "Odium de Thanatos" WHERE `ID` = 1709;
UPDATE `mob_db` SET `kName` = "Despero de Thanatos", `iName` = "Despero de Thanatos" WHERE `ID` = 1710;
UPDATE `mob_db` SET `kName` = "Maero de Thanatos", `iName` = "Maero de Thanatos" WHERE `ID` = 1711;
UPDATE `mob_db` SET `kName` = "Pesar de Thanatos", `iName` = "Pesar de Thanatos" WHERE `ID` = 1712;
UPDATE `mob_db` SET `kName` = "Acidus", `iName` = "Acidus" WHERE `ID` = 1713;
UPDATE `mob_db` SET `kName` = "Ferus", `iName` = "Ferus" WHERE `ID` = 1714;
UPDATE `mob_db` SET `kName` = "Novus", `iName` = "Novus" WHERE `ID` = 1715;
UPDATE `mob_db` SET `kName` = "Acidus", `iName` = "Acidus" WHERE `ID` = 1716;
UPDATE `mob_db` SET `kName` = "Ferus", `iName` = "Ferus" WHERE `ID` = 1717;
UPDATE `mob_db` SET `kName` = "Novus", `iName` = "Novus" WHERE `ID` = 1718;
UPDATE `mob_db` SET `kName` = "Detardeurus", `iName` = "Detardeurus" WHERE `ID` = 1719;
UPDATE `mob_db` SET `kName` = "Hydrolancer", `iName` = "Hydrolancer" WHERE `ID` = 1720;
UPDATE `mob_db` SET `kName` = "Ovo de Dragão", `iName` = "Ovo de Dragão" WHERE `ID` = 1721;
UPDATE `mob_db` SET `kName` = "Jakk", `iName` = "Jakk" WHERE `ID` = 1722;
UPDATE `mob_db` SET `kName` = "Cecil Damon", `iName` = "Cecil Damon" WHERE `ID` = 1723;
UPDATE `mob_db` SET `kName` = "Canhão de Fóton", `iName` = "Canhão de Fóton" WHERE `ID` = 1724;
UPDATE `mob_db` SET `kName` = "Poring", `iName` = "Poring" WHERE `ID` = 1725;
UPDATE `mob_db` SET `kName` = "Lunático", `iName` = "Lunático" WHERE `ID` = 1726;
UPDATE `mob_db` SET `kName` = "Bebê Selvagem", `iName` = "Bebê Selvagem" WHERE `ID` = 1727;
UPDATE `mob_db` SET `kName` = "Lobo do Deserto Bebe", `iName` = "Lobo do Deserto Bebe" WHERE `ID` = 1728;
UPDATE `mob_db` SET `kName` = "Bafomé Jr.", `iName` = "Bafomé Jr." WHERE `ID` = 1729;
UPDATE `mob_db` SET `kName` = "Deviruchi", `iName` = "Deviruchi" WHERE `ID` = 1730;
UPDATE `mob_db` SET `kName` = "Doppelganger", `iName` = "Doppelganger" WHERE `ID` = 1731;
UPDATE `mob_db` SET `kName` = "Baú de Tesouro", `iName` = "Baú de Tesouro" WHERE `ID` = 1732;
UPDATE `mob_db` SET `kName` = "Kiel", `iName` = "Kiel" WHERE `ID` = 1733;
UPDATE `mob_db` SET `kName` = "Kiel D-01", `iName` = "Kiel D-01" WHERE `ID` = 1734;
UPDATE `mob_db` SET `kName` = "Alicel", `iName` = "Alicel" WHERE `ID` = 1735;
UPDATE `mob_db` SET `kName` = "Aliot", `iName` = "Aliot" WHERE `ID` = 1736;
UPDATE `mob_db` SET `kName` = "Aliza", `iName` = "Aliza" WHERE `ID` = 1737;
UPDATE `mob_db` SET `kName` = "Constante", `iName` = "Constante" WHERE `ID` = 1738;
UPDATE `mob_db` SET `kName` = "Alicel", `iName` = "Alicel" WHERE `ID` = 1739;
UPDATE `mob_db` SET `kName` = "Aliot", `iName` = "Aliot" WHERE `ID` = 1740;
UPDATE `mob_db` SET `kName` = "Cookie", `iName` = "Cookie" WHERE `ID` = 1741;
UPDATE `mob_db` SET `kName` = "Carat", `iName` = "Carat" WHERE `ID` = 1742;
UPDATE `mob_db` SET `kName` = "Presente", `iName` = "Presente" WHERE `ID` = 1743;
UPDATE `mob_db` SET `kName` = "Rosa Selvagem", `iName` = "Rosa Selvagem" WHERE `ID` = 1744;
UPDATE `mob_db` SET `kName` = "Constante", `iName` = "Constante" WHERE `ID` = 1745;
UPDATE `mob_db` SET `kName` = "Aliza", `iName` = "Aliza" WHERE `ID` = 1746;
UPDATE `mob_db` SET `kName` = "Serpente", `iName` = "Serpente" WHERE `ID` = 1747;
UPDATE `mob_db` SET `kName` = "Anaconda", `iName` = "Anaconda" WHERE `ID` = 1748;
UPDATE `mob_db` SET `kName` = "Medusa", `iName` = "Medusa" WHERE `ID` = 1749;
UPDATE `mob_db` SET `kName` = "Planta Vermelha", `iName` = "Planta Vermelha" WHERE `ID` = 1750;
UPDATE `mob_db` SET `kName` = "Valquíria Randgris", `iName` = "Valquíria Randgris" WHERE `ID` = 1751;
UPDATE `mob_db` SET `kName` = "Skogul", `iName` = "Skogul" WHERE `ID` = 1752;
UPDATE `mob_db` SET `kName` = "Frus", `iName` = "Frus" WHERE `ID` = 1753;
UPDATE `mob_db` SET `kName` = "Skeggiold", `iName` = "Skeggiold" WHERE `ID` = 1754;
UPDATE `mob_db` SET `kName` = "Skeggiold", `iName` = "Skeggiold" WHERE `ID` = 1755;
UPDATE `mob_db` SET `kName` = "Hydrolancer", `iName` = "Hydrolancer" WHERE `ID` = 1756;
UPDATE `mob_db` SET `kName` = "Acidus", `iName` = "Acidus" WHERE `ID` = 1757;
UPDATE `mob_db` SET `kName` = "Ferus", `iName` = "Ferus" WHERE `ID` = 1758;
UPDATE `mob_db` SET `kName` = "Acidus", `iName` = "Acidus" WHERE `ID` = 1759;
UPDATE `mob_db` SET `kName` = "Ferus", `iName` = "Ferus" WHERE `ID` = 1760;
UPDATE `mob_db` SET `kName` = "Skogul", `iName` = "Skogul" WHERE `ID` = 1761;
UPDATE `mob_db` SET `kName` = "Frus", `iName` = "Frus" WHERE `ID` = 1762;
UPDATE `mob_db` SET `kName` = "Skeggiold", `iName` = "Skeggiold" WHERE `ID` = 1763;
UPDATE `mob_db` SET `kName` = "Skeggiold", `iName` = "Skeggiold" WHERE `ID` = 1764;
UPDATE `mob_db` SET `kName` = "Valkyrie", `iName` = "Valkyrie" WHERE `ID` = 1765;
UPDATE `mob_db` SET `kName` = "Angeling", `iName` = "Angeling" WHERE `ID` = 1766;
UPDATE `mob_db` SET `kName` = "Deviling", `iName` = "Deviling" WHERE `ID` = 1767;
UPDATE `mob_db` SET `kName` = "Pesar Noturno", `iName` = "Pesar Noturno" WHERE `ID` = 1768;
UPDATE `mob_db` SET `kName` = "Agav", `iName` = "Agav" WHERE `ID` = 1769;
UPDATE `mob_db` SET `kName` = "Echio", `iName` = "Echio" WHERE `ID` = 1770;
UPDATE `mob_db` SET `kName` = "Vanberk", `iName` = "Vanberk" WHERE `ID` = 1771;
UPDATE `mob_db` SET `kName` = "Isilla", `iName` = "Isilla" WHERE `ID` = 1772;
UPDATE `mob_db` SET `kName` = "Hodremlin", `iName` = "Hodremlin" WHERE `ID` = 1773;
UPDATE `mob_db` SET `kName` = "Rastreador", `iName` = "Rastreador" WHERE `ID` = 1774;
UPDATE `mob_db` SET `kName` = "Yeti", `iName` = "Yeti" WHERE `ID` = 1775;
UPDATE `mob_db` SET `kName` = "Siroma", `iName` = "Siroma" WHERE `ID` = 1776;
UPDATE `mob_db` SET `kName` = "Titã de Gelo", `iName` = "Titã de Gelo" WHERE `ID` = 1777;
UPDATE `mob_db` SET `kName` = "Gazeti", `iName` = "Gazeti" WHERE `ID` = 1778;
UPDATE `mob_db` SET `kName` = "Ktullanux", `iName` = "Ktullanux" WHERE `ID` = 1779;
UPDATE `mob_db` SET `kName` = "Muscipular", `iName` = "Muscipular" WHERE `ID` = 1780;
UPDATE `mob_db` SET `kName` = "Drosera", `iName` = "Drosera" WHERE `ID` = 1781;
UPDATE `mob_db` SET `kName` = "Roween", `iName` = "Roween" WHERE `ID` = 1782;
UPDATE `mob_db` SET `kName` = "Galion", `iName` = "Galion" WHERE `ID` = 1783;
UPDATE `mob_db` SET `kName` = "Stapo", `iName` = "Stapo" WHERE `ID` = 1784;
UPDATE `mob_db` SET `kName` = "Atroce", `iName` = "Atroce" WHERE `ID` = 1785;
UPDATE `mob_db` SET `kName` = "Agav", `iName` = "Agav" WHERE `ID` = 1786;
UPDATE `mob_db` SET `kName` = "Echio", `iName` = "Echio" WHERE `ID` = 1787;
UPDATE `mob_db` SET `kName` = "Titã de Gelo", `iName` = "Titã de Gelo" WHERE `ID` = 1788;
UPDATE `mob_db` SET `kName` = "Estalactitico", `iName` = "Estalactitico" WHERE `ID` = 1789;
UPDATE `mob_db` SET `kName` = "Rafflesia", `iName` = "Rafflesia" WHERE `ID` = 1790;
UPDATE `mob_db` SET `kName` = "Galion", `iName` = "Galion" WHERE `ID` = 1791;
UPDATE `mob_db` SET `kName` = "Bola de Futebol", `iName` = "Bola de Futebol" WHERE `ID` = 1792;
UPDATE `mob_db` SET `kName` = "Megalith", `iName` = "Megalith" WHERE `ID` = 1793;
UPDATE `mob_db` SET `kName` = "Roween", `iName` = "Roween" WHERE `ID` = 1794;
UPDATE `mob_db` SET `kName` = "Cavaleiro Sanguinário", `iName` = "Cavaleiro Sanguinário" WHERE `ID` = 1795;
UPDATE `mob_db` SET `kName` = "Aunoe", `iName` = "Aunoe" WHERE `ID` = 1796;
UPDATE `mob_db` SET `kName` = "Fanat", `iName` = "Fanat" WHERE `ID` = 1797;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1798;
UPDATE `mob_db` SET `kName` = "Lorde Seyren", `iName` = "Lorde Seyren" WHERE `ID` = 1799;
UPDATE `mob_db` SET `kName` = "Algoz Eremes", `iName` = "Algoz Eremes" WHERE `ID` = 1800;
UPDATE `mob_db` SET `kName` = "Mestre-Ferreiro Howard", `iName` = "Mestre-Ferreiro Howard" WHERE `ID` = 1801;
UPDATE `mob_db` SET `kName` = "Suma-Sacerdotisa Margaretha", `iName` = "Suma-Sacerdotisa Margaretha" WHERE `ID` = 1802;
UPDATE `mob_db` SET `kName` = "Atiradora de Elite Cecil", `iName` = "Atiradora de Elite Cecil" WHERE `ID` = 1803;
UPDATE `mob_db` SET `kName` = "Arquimaga Kathryne", `iName` = "Arquimaga Kathryne" WHERE `ID` = 1804;
UPDATE `mob_db` SET `kName` = "Lorde Seyren", `iName` = "Lorde Seyren" WHERE `ID` = 1805;
UPDATE `mob_db` SET `kName` = "Algoz Eremes", `iName` = "Algoz Eremes" WHERE `ID` = 1806;
UPDATE `mob_db` SET `kName` = "Mestre-Ferreiro Howard", `iName` = "Mestre-Ferreiro Howard" WHERE `ID` = 1807;
UPDATE `mob_db` SET `kName` = "Suma-Sacerdotisa Margaretha", `iName` = "Suma-Sacerdotisa Margaretha" WHERE `ID` = 1808;
UPDATE `mob_db` SET `kName` = "Atiradora de Elite Cecil", `iName` = "Atiradora de Elite Cecil" WHERE `ID` = 1809;
UPDATE `mob_db` SET `kName` = "Arquimaga Kathryne", `iName` = "Arquimaga Kathryne" WHERE `ID` = 1810;
UPDATE `mob_db` SET `kName` = "Fumacento", `iName` = "Fumacento" WHERE `ID` = 1811;
UPDATE `mob_db` SET `kName` = "Lude", `iName` = "Lude" WHERE `ID` = 1812;
UPDATE `mob_db` SET `kName` = "Hydrolancer", `iName` = "Hydrolancer" WHERE `ID` = 1813;
UPDATE `mob_db` SET `kName` = "Flor do Luar", `iName` = "Flor do Luar" WHERE `ID` = 1814;
UPDATE `mob_db` SET `kName` = "Bolinho de Arroz", `iName` = "Bolinho de Arroz" WHERE `ID` = 1815;
UPDATE `mob_db` SET `kName` = "Gourd", `iName` = "Gourd" WHERE `ID` = 1816;
UPDATE `mob_db` SET `kName` = "Detardeurus", `iName` = "Detardeurus" WHERE `ID` = 1817;
UPDATE `mob_db` SET `kName` = "Alarme", `iName` = "Alarme" WHERE `ID` = 1818;
UPDATE `mob_db` SET `kName` = "Bathory", `iName` = "Bathory" WHERE `ID` = 1819;
UPDATE `mob_db` SET `kName` = "Pé Grande", `iName` = "Pé Grande" WHERE `ID` = 1820;
UPDATE `mob_db` SET `kName` = "Lobo do Deserto", `iName` = "Lobo do Deserto" WHERE `ID` = 1821;
UPDATE `mob_db` SET `kName` = "Deviruchi", `iName` = "Deviruchi" WHERE `ID` = 1822;
UPDATE `mob_db` SET `kName` = "Congelador", `iName` = "Congelador" WHERE `ID` = 1823;
UPDATE `mob_db` SET `kName` = "Filhote de Hatii", `iName` = "Filhote de Hatii" WHERE `ID` = 1824;
UPDATE `mob_db` SET `kName` = "Goblin Natalino", `iName` = "Goblin Natalino" WHERE `ID` = 1825;
UPDATE `mob_db` SET `kName` = "Névoa", `iName` = "Névoa" WHERE `ID` = 1826;
UPDATE `mob_db` SET `kName` = "Sasquatch", `iName` = "Sasquatch" WHERE `ID` = 1827;
UPDATE `mob_db` SET `kName` = "Gullinbrusti", `iName` = "Gullinbrusti" WHERE `ID` = 1828;
UPDATE `mob_db` SET `kName` = "Espadachim Guardião", `iName` = "Espadachim Guardião" WHERE `ID` = 1829;
UPDATE `mob_db` SET `kName` = "Arqueiro Guardião", `iName` = "Arqueiro Guardião" WHERE `ID` = 1830;
UPDATE `mob_db` SET `kName` = "Salamandra", `iName` = "Salamandra" WHERE `ID` = 1831;
UPDATE `mob_db` SET `kName` = "Ifrit", `iName` = "Ifrit" WHERE `ID` = 1832;
UPDATE `mob_db` SET `kName` = "Kasa", `iName` = "Kasa" WHERE `ID` = 1833;
UPDATE `mob_db` SET `kName` = "Salamandra", `iName` = "Salamandra" WHERE `ID` = 1834;
UPDATE `mob_db` SET `kName` = "Kasa", `iName` = "Kasa" WHERE `ID` = 1835;
UPDATE `mob_db` SET `kName` = "Magmaring", `iName` = "Magmaring" WHERE `ID` = 1836;
UPDATE `mob_db` SET `kName` = "Imp", `iName` = "Imp" WHERE `ID` = 1837;
UPDATE `mob_db` SET `kName` = "Golpeador", `iName` = "Golpeador" WHERE `ID` = 1838;
UPDATE `mob_db` SET `kName` = "Byorgue", `iName` = "Byorgue" WHERE `ID` = 1839;
UPDATE `mob_db` SET `kName` = "Grande Selvagem", `iName` = "Grande Selvagem" WHERE `ID` = 1840;
UPDATE `mob_db` SET `kName` = "Serpente", `iName` = "Serpente" WHERE `ID` = 1841;
UPDATE `mob_db` SET `kName` = "Anaconda", `iName` = "Anaconda" WHERE `ID` = 1842;
UPDATE `mob_db` SET `kName` = "Sorrateiro", `iName` = "Sorrateiro" WHERE `ID` = 1843;
UPDATE `mob_db` SET `kName` = "Isis", `iName` = "Isis" WHERE `ID` = 1844;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1845;
UPDATE `mob_db` SET `kName` = "Emperium", `iName` = "Emperium" WHERE `ID` = 1846;
UPDATE `mob_db` SET `kName` = "Poring", `iName` = "Poring" WHERE `ID` = 1847;
UPDATE `mob_db` SET `kName` = "Bafomé", `iName` = "Bafomé" WHERE `ID` = 1848;
UPDATE `mob_db` SET `kName` = "Osíris", `iName` = "Osíris" WHERE `ID` = 1849;
UPDATE `mob_db` SET `kName` = "Orc Herói", `iName` = "Orc Herói" WHERE `ID` = 1850;
UPDATE `mob_db` SET `kName` = "Yakuza", `iName` = "Yakuza" WHERE `ID` = 1851;
UPDATE `mob_db` SET `kName` = "Angeling", `iName` = "Angeling" WHERE `ID` = 1852;
UPDATE `mob_db` SET `kName` = "Deviling", `iName` = "Deviling" WHERE `ID` = 1853;
UPDATE `mob_db` SET `kName` = "Muka", `iName` = "Muka" WHERE `ID` = 1854;
UPDATE `mob_db` SET `kName` = "Esporo Venenoso", `iName` = "Esporo Venenoso" WHERE `ID` = 1855;
UPDATE `mob_db` SET `kName` = "Magnólia", `iName` = "Magnólia" WHERE `ID` = 1856;
UPDATE `mob_db` SET `kName` = "Marin", `iName` = "Marin" WHERE `ID` = 1857;
UPDATE `mob_db` SET `kName` = "Plankton", `iName` = "Plankton" WHERE `ID` = 1858;
UPDATE `mob_db` SET `kName` = "Mandrágora", `iName` = "Mandrágora" WHERE `ID` = 1859;
UPDATE `mob_db` SET `kName` = "Koko", `iName` = "Koko" WHERE `ID` = 1860;
UPDATE `mob_db` SET `kName` = "Choco", `iName` = "Choco" WHERE `ID` = 1861;
UPDATE `mob_db` SET `kName` = "Martin", `iName` = "Martin" WHERE `ID` = 1862;
UPDATE `mob_db` SET `kName` = "Coelho", `iName` = "Coelho" WHERE `ID` = 1863;
UPDATE `mob_db` SET `kName` = "Massacre", `iName` = "Massacre" WHERE `ID` = 1864;
UPDATE `mob_db` SET `kName` = "Zumbi Dilacerado", `iName` = "Zumbi Dilacerado" WHERE `ID` = 1865;
UPDATE `mob_db` SET `kName` = "Cão Infernal", `iName` = "Cão Infernal" WHERE `ID` = 1866;
UPDATE `mob_db` SET `kName` = "Banshee", `iName` = "Banshee" WHERE `ID` = 1867;
UPDATE `mob_db` SET `kName` = "Banshee", `iName` = "Banshee" WHERE `ID` = 1868;
UPDATE `mob_db` SET `kName` = "Crânio Flamejante", `iName` = "Crânio Flamejante" WHERE `ID` = 1869;
UPDATE `mob_db` SET `kName` = "Necromante", `iName` = "Necromante" WHERE `ID` = 1870;
UPDATE `mob_db` SET `kName` = "Bispo Decadente", `iName` = "Bispo Decadente" WHERE `ID` = 1871;
UPDATE `mob_db` SET `kName` = "Mosca Infernal", `iName` = "Mosca Infernal" WHERE `ID` = 1872;
UPDATE `mob_db` SET `kName` = "Belzebu", `iName` = "Belzebu" WHERE `ID` = 1873;
UPDATE `mob_db` SET `kName` = "Belzebu", `iName` = "Belzebu" WHERE `ID` = 1874;
UPDATE `mob_db` SET `kName` = "Tristan III", `iName` = "Tristan III" WHERE `ID` = 1875;
UPDATE `mob_db` SET `kName` = "Senhor dos Mortos", `iName` = "Senhor dos Mortos" WHERE `ID` = 1876;
UPDATE `mob_db` SET `kName` = "Cristal", `iName` = "Cristal" WHERE `ID` = 1877;
UPDATE `mob_db` SET `kName` = "Planta Brilhante", `iName` = "Planta Brilhante" WHERE `ID` = 1878;
UPDATE `mob_db` SET `kName` = "Coelho", `iName` = "Coelho" WHERE `ID` = 1879;
UPDATE `mob_db` SET `kName` = "Leshij", `iName` = "Leshij" WHERE `ID` = 1880;
UPDATE `mob_db` SET `kName` = "Les", `iName` = "Les" WHERE `ID` = 1881;
UPDATE `mob_db` SET `kName` = "Baba-Yaga", `iName` = "Baba-Yaga" WHERE `ID` = 1882;
UPDATE `mob_db` SET `kName` = "Kikimora", `iName` = "Kikimora" WHERE `ID` = 1883;
UPDATE `mob_db` SET `kName` = "Mavka", `iName` = "Mavka" WHERE `ID` = 1884;
UPDATE `mob_db` SET `kName` = "Gorynych", `iName` = "Gorynych" WHERE `ID` = 1885;
UPDATE `mob_db` SET `kName` = "Mavka", `iName` = "Mavka" WHERE `ID` = 1886;
UPDATE `mob_db` SET `kName` = "Congelador", `iName` = "Congelador" WHERE `ID` = 1887;
UPDATE `mob_db` SET `kName` = "Filhote de Hatii", `iName` = "Filhote de Hatii" WHERE `ID` = 1888;
UPDATE `mob_db` SET `kName` = "Guarda de Marozka", `iName` = "Guarda de Marozka" WHERE `ID` = 1889;
UPDATE `mob_db` SET `kName` = "Koshei o Imortal", `iName` = "Koshei o Imortal" WHERE `ID` = 1890;
UPDATE `mob_db` SET `kName` = "Valkyrie", `iName` = "Valkyrie" WHERE `ID` = 1891;
UPDATE `mob_db` SET `kName` = "Loli Ruri", `iName` = "Loli Ruri" WHERE `ID` = 1892;
UPDATE `mob_db` SET `kName` = "Cavaleiro do Abismo", `iName` = "Cavaleiro do Abismo" WHERE `ID` = 1893;
UPDATE `mob_db` SET `kName` = "Pouring", `iName` = "Pouring" WHERE `ID` = 1894;
UPDATE `mob_db` SET `kName` = "Seyren Windsor", `iName` = "Seyren Windsor" WHERE `ID` = 1895;
UPDATE `mob_db` SET `kName` = "Kathryne Keyron", `iName` = "Kathryne Keyron" WHERE `ID` = 1896;
UPDATE `mob_db` SET `kName` = "Bafomé", `iName` = "Bafomé" WHERE `ID` = 1897;
UPDATE `mob_db` SET `kName` = "Zumbi", `iName` = "Zumbi" WHERE `ID` = 1898;
UPDATE `mob_db` SET `kName` = "Espadachim Guardião", `iName` = "Espadachim Guardião" WHERE `ID` = 1899;
UPDATE `mob_db` SET `kName` = "Condor", `iName` = "Condor" WHERE `ID` = 1901;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1902;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1903;
UPDATE `mob_db` SET `kName` = "Bomb Poring", `iName` = "Bomb Poring" WHERE `ID` = 1904;
UPDATE `mob_db` SET `kName` = "Barricada", `iName` = "Barricada" WHERE `ID` = 1905;
UPDATE `mob_db` SET `kName` = "Barricada", `iName` = "Barricada" WHERE `ID` = 1906;
UPDATE `mob_db` SET `kName` = "Runa Guardiã", `iName` = "Runa Guardiã" WHERE `ID` = 1907;
UPDATE `mob_db` SET `kName` = "Runa Guardiã", `iName` = "Runa Guardiã" WHERE `ID` = 1908;
UPDATE `mob_db` SET `kName` = "Armazém de Comida", `iName` = "Armazém de Comida" WHERE `ID` = 1909;
UPDATE `mob_db` SET `kName` = "Depósito de Comida", `iName` = "Depósito de Comida" WHERE `ID` = 1910;
UPDATE `mob_db` SET `kName` = "Bandeira Neutra", `iName` = "Bandeira Neutra" WHERE `ID` = 1911;
UPDATE `mob_db` SET `kName` = "Bandeira de Leão", `iName` = "Bandeira de Leão" WHERE `ID` = 1912;
UPDATE `mob_db` SET `kName` = "Bandeira de Águia", `iName` = "Bandeira de Águia" WHERE `ID` = 1913;
UPDATE `mob_db` SET `kName` = "Cristal Azul", `iName` = "Cristal Azul" WHERE `ID` = 1914;
UPDATE `mob_db` SET `kName` = "Cristal Cor-de-Rosa", `iName` = "Cristal Cor-de-Rosa" WHERE `ID` = 1915;
UPDATE `mob_db` SET `kName` = "Imperador de Morroc", `iName` = "Imperador de Morroc" WHERE `ID` = 1916;
UPDATE `mob_db` SET `kName` = "Morroc Ferido", `iName` = "Morroc Ferido" WHERE `ID` = 1917;
UPDATE `mob_db` SET `kName` = "Sombra da Inveja", `iName` = "Sombra da Inveja" WHERE `ID` = 1918;
UPDATE `mob_db` SET `kName` = "Sombra da Gula", `iName` = "Sombra da Gula" WHERE `ID` = 1919;
UPDATE `mob_db` SET `kName` = "Sombra da Vaidade", `iName` = "Sombra da Vaidade" WHERE `ID` = 1920;
UPDATE `mob_db` SET `kName` = "Sombra da Ira", `iName` = "Sombra da Ira" WHERE `ID` = 1921;
UPDATE `mob_db` SET `kName` = "Sombra da Inveja", `iName` = "Sombra da Inveja" WHERE `ID` = 1922;
UPDATE `mob_db` SET `kName` = "Sombra da Gula", `iName` = "Sombra da Gula" WHERE `ID` = 1923;
UPDATE `mob_db` SET `kName` = "Sombra da Vaidade", `iName` = "Sombra da Vaidade" WHERE `ID` = 1924;
UPDATE `mob_db` SET `kName` = "Sombra da Ira", `iName` = "Sombra da Ira" WHERE `ID` = 1925;
UPDATE `mob_db` SET `kName` = "Jakk", `iName` = "Jakk" WHERE `ID` = 1926;
UPDATE `mob_db` SET `kName` = "Sussurro", `iName` = "Sussurro" WHERE `ID` = 1927;
UPDATE `mob_db` SET `kName` = "Deviruchi", `iName` = "Deviruchi" WHERE `ID` = 1928;
UPDATE `mob_db` SET `kName` = "Bafomé", `iName` = "Bafomé" WHERE `ID` = 1929;
UPDATE `mob_db` SET `kName` = "Piamete", `iName` = "Piamete" WHERE `ID` = 1930;
UPDATE `mob_db` SET `kName` = "Donzela do Desejo", `iName` = "Donzela do Desejo" WHERE `ID` = 1931;
UPDATE `mob_db` SET `kName` = "Segurança do Jardim", `iName` = "Segurança do Jardim" WHERE `ID` = 1932;
UPDATE `mob_db` SET `kName` = "Vigia do Jardim", `iName` = "Vigia do Jardim" WHERE `ID` = 1933;
UPDATE `mob_db` SET `kName` = "Flor Azul", `iName` = "Flor Azul" WHERE `ID` = 1934;
UPDATE `mob_db` SET `kName` = "Flor Vermelha", `iName` = "Flor Vermelha" WHERE `ID` = 1935;
UPDATE `mob_db` SET `kName` = "Flor Amarela", `iName` = "Flor Amarela" WHERE `ID` = 1936;
UPDATE `mob_db` SET `kName` = "Constante", `iName` = "Constante" WHERE `ID` = 1937;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1938;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1939;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1940;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1941;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1942;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1943;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1944;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1945;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1946;
UPDATE `mob_db` SET `kName` = "Piamete", `iName` = "Piamete" WHERE `ID` = 1947;
UPDATE `mob_db` SET `kName` = "Egnigem Cenia", `iName` = "Egnigem Cenia" WHERE `ID` = 1948;
UPDATE `mob_db` SET `kName` = "Guardião do Campo", `iName` = "Guardião do Campo" WHERE `ID` = 1949;
UPDATE `mob_db` SET `kName` = "Guardião do Campo", `iName` = "Guardião do Campo" WHERE `ID` = 1950;
UPDATE `mob_db` SET `kName` = "Cristal", `iName` = "Cristal" WHERE `ID` = 1951;
UPDATE `mob_db` SET `kName` = "Cristal", `iName` = "Cristal" WHERE `ID` = 1952;
UPDATE `mob_db` SET `kName` = "Cristal", `iName` = "Cristal" WHERE `ID` = 1953;
UPDATE `mob_db` SET `kName` = "Cristal", `iName` = "Cristal" WHERE `ID` = 1954;
UPDATE `mob_db` SET `kName` = "Baú do Tesouro", `iName` = "Baú do Tesouro" WHERE `ID` = 1955;
UPDATE `mob_db` SET `kName` = "Naght Sieger", `iName` = "Naght Sieger" WHERE `ID` = 1956;
UPDATE `mob_db` SET `kName` = "Entweihen Crothen", `iName` = "Entweihen Crothen" WHERE `ID` = 1957;
UPDATE `mob_db` SET `kName` = "Esqueleto Espinhoso", `iName` = "Esqueleto Espinhoso" WHERE `ID` = 1958;
UPDATE `mob_db` SET `kName` = "Esqueleto Espinhoso", `iName` = "Esqueleto Espinhoso" WHERE `ID` = 1959;
UPDATE `mob_db` SET `kName` = "Esqueleto Espinhoso", `iName` = "Esqueleto Espinhoso" WHERE `ID` = 1960;
UPDATE `mob_db` SET `kName` = "Esqueleto Espinhoso", `iName` = "Esqueleto Espinhoso" WHERE `ID` = 1961;
UPDATE `mob_db` SET `kName` = "Ladrão Natalino", `iName` = "Ladrão Natalino" WHERE `ID` = 1962;
UPDATE `mob_db` SET `kName` = "Boneca do Ano Novo", `iName` = "Boneca do Ano Novo" WHERE `ID` = 1963;
UPDATE `mob_db` SET `kName` = "Pesadelo", `iName` = "Pesadelo" WHERE `ID` = 1964;
UPDATE `mob_db` SET `kName` = "Rosa Selvagem", `iName` = "Rosa Selvagem" WHERE `ID` = 1965;
UPDATE `mob_db` SET `kName` = "Doppelganger", `iName` = "Doppelganger" WHERE `ID` = 1966;
UPDATE `mob_db` SET `kName` = "Egnigem Cenia", `iName` = "Egnigem Cenia" WHERE `ID` = 1967;
UPDATE `mob_db` SET `kName` = "Strouf", `iName` = "Strouf" WHERE `ID` = 1968;
UPDATE `mob_db` SET `kName` = "Cavalo-Marinho", `iName` = "Cavalo-Marinho" WHERE `ID` = 1969;
UPDATE `mob_db` SET `kName` = "Obeaune", `iName` = "Obeaune" WHERE `ID` = 1970;
UPDATE `mob_db` SET `kName` = "Vadon", `iName` = "Vadon" WHERE `ID` = 1971;
UPDATE `mob_db` SET `kName` = "Marina", `iName` = "Marina" WHERE `ID` = 1972;
UPDATE `mob_db` SET `kName` = "Poring", `iName` = "Poring" WHERE `ID` = 1973;
UPDATE `mob_db` SET `kName` = "Senhora das Banshees", `iName` = "Senhora das Banshees" WHERE `ID` = 1974;
UPDATE `mob_db` SET `kName` = "Mestre Beholder", `iName` = "Mestre Beholder" WHERE `ID` = 1975;
UPDATE `mob_db` SET `kName` = "Cobalto", `iName` = "Cobalto" WHERE `ID` = 1976;
UPDATE `mob_db` SET `kName` = "Metaling Pesado", `iName` = "Metaling Pesado" WHERE `ID` = 1977;
UPDATE `mob_db` SET `kName` = "Apocalipse Infernal", `iName` = "Apocalipse Infernal" WHERE `ID` = 1978;
UPDATE `mob_db` SET `kName` = "Zakudam", `iName` = "Zakudam" WHERE `ID` = 1979;
UPDATE `mob_db` SET `kName` = "Kublin", `iName` = "Kublin" WHERE `ID` = 1980;
UPDATE `mob_db` SET `kName` = "Soldado Orc", `iName` = "Soldado Orc" WHERE `ID` = 1981;
UPDATE `mob_db` SET `kName` = "Orc Arqueiro", `iName` = "Orc Arqueiro" WHERE `ID` = 1982;
UPDATE `mob_db` SET `kName` = "Zenorc", `iName` = "Zenorc" WHERE `ID` = 1983;
UPDATE `mob_db` SET `kName` = "Guarda de Elite Orc", `iName` = "Guarda de Elite Orc" WHERE `ID` = 1984;
UPDATE `mob_db` SET `kName` = "Dente_de_Leão", `iName` = "Dente_de_Leão" WHERE `ID` = 1985;
UPDATE `mob_db` SET `kName` = "Tatacho", `iName` = "Tatacho" WHERE `ID` = 1986;
UPDATE `mob_db` SET `kName` = "Centopéia", `iName` = "Centopéia" WHERE `ID` = 1987;
UPDATE `mob_db` SET `kName` = "Nepenthes", `iName` = "Nepenthes" WHERE `ID` = 1988;
UPDATE `mob_db` SET `kName` = "Leão da Montanha", `iName` = "Leão da Montanha" WHERE `ID` = 1989;
UPDATE `mob_db` SET `kName` = "Mamute Rochoso", `iName` = "Mamute Rochoso" WHERE `ID` = 1990;
UPDATE `mob_db` SET `kName` = "Leão de Vinhas", `iName` = "Leão de Vinhas" WHERE `ID` = 1991;
UPDATE `mob_db` SET `kName` = "Cornus", `iName` = "Cornus" WHERE `ID` = 1992;
UPDATE `mob_db` SET `kName` = "Naga", `iName` = "Naga" WHERE `ID` = 1993;
UPDATE `mob_db` SET `kName` = "Vespa Vagalume", `iName` = "Vespa Vagalume" WHERE `ID` = 1994;
UPDATE `mob_db` SET `kName` = "Pinguicula", `iName` = "Pinguicula" WHERE `ID` = 1995;
UPDATE `mob_db` SET `kName` = "Tatacho", `iName` = "Tatacho" WHERE `ID` = 1997;
UPDATE `mob_db` SET `kName` = "Leão da Montanha", `iName` = "Leão da Montanha" WHERE `ID` = 1998;
UPDATE `mob_db` SET `kName` = "Larva de Centopéia", `iName` = "Larva de Centopéia" WHERE `ID` = 1999;
UPDATE `mob_db` SET `kName` = "Woomawang", `iName` = "Woomawang" WHERE `ID` = 2008;
UPDATE `mob_db` SET `kName` = "Woomawang", `iName` = "Woomawang" WHERE `ID` = 2009;
UPDATE `mob_db` SET `kName` = "Ox", `iName` = "Ox" WHERE `ID` = 2010;
UPDATE `mob_db` SET `kName` = "Draco", `iName` = "Draco" WHERE `ID` = 2013;
UPDATE `mob_db` SET `kName` = "Ovo de Draco", `iName` = "Ovo de Draco" WHERE `ID` = 2014;
UPDATE `mob_db` SET `kName` = "Pinguicula Sombria", `iName` = "Pinguicula Sombria" WHERE `ID` = 2015;
UPDATE `mob_db` SET `kName` = "Elemental da Água", `iName` = "Elemental da Água" WHERE `ID` = 2016;
UPDATE `mob_db` SET `kName` = "Rata", `iName` = "Rata" WHERE `ID` = 2017;
UPDATE `mob_db` SET `kName` = "Duneyrr", `iName` = "Duneyrr" WHERE `ID` = 2018;
UPDATE `mob_db` SET `kName` = "Árvore Anciã", `iName` = "Árvore Anciã" WHERE `ID` = 2019;
UPDATE `mob_db` SET `kName` = "Ryncho", `iName` = "Ryncho" WHERE `ID` = 2020;
UPDATE `mob_db` SET `kName` = "Phylla", `iName` = "Phylla" WHERE `ID` = 2021;
UPDATE `mob_db` SET `kName` = "Sombra de Nidhogg", `iName` = "Sombra de Nidhogg" WHERE `ID` = 2022;
UPDATE `mob_db` SET `kName` = "Sombra Obscura", `iName` = "Sombra Obscura" WHERE `ID` = 2023;
UPDATE `mob_db` SET `kName` = "Golem de Bradium", `iName` = "Golem de Bradium" WHERE `ID` = 2024;
UPDATE `mob_db` SET `kName` = "Membro Dandelion Fugitivo", `iName` = "Membro Dandelion Fugitivo" WHERE `ID` = 2026;
UPDATE `mob_db` SET `kName` = "Sombra Obscura", `iName` = "Sombra Obscura" WHERE `ID` = 2027;
UPDATE `mob_db` SET `kName` = "Hiden Priest", `iName` = "Hiden Priest" WHERE `ID` = 2030;
UPDATE `mob_db` SET `kName` = "Dandelion", `iName` = "Dandelion" WHERE `ID` = 2031;
UPDATE `mob_db` SET `kName` = "Silver Sniper", `iName` = "Silver Sniper" WHERE `ID` = 2042;
UPDATE `mob_db` SET `kName` = "Magic Decoy", `iName` = "Magic Decoy" WHERE `ID` = 2043;
UPDATE `mob_db` SET `kName` = "Magic Decoy", `iName` = "Magic Decoy" WHERE `ID` = 2044;
UPDATE `mob_db` SET `kName` = "Magic Decoy", `iName` = "Magic Decoy" WHERE `ID` = 2045;
UPDATE `mob_db` SET `kName` = "Magic Decoy", `iName` = "Magic Decoy" WHERE `ID` = 2046;
UPDATE `mob_db` SET `kName` = "Naga", `iName` = "Naga" WHERE `ID` = 2047;
UPDATE `mob_db` SET `kName` = "Golem de Bradium", `iName` = "Golem de Bradium" WHERE `ID` = 2049;
UPDATE `mob_db` SET `kName` = "Cãibra", `iName` = "Cãibra" WHERE `ID` = 2057;
UPDATE `mob_db` SET `kName` = "Boitatá", `iName` = "Boitatá" WHERE `ID` = 2068;
UPDATE `mob_db` SET `kName` = "Iara", `iName` = "Iara" WHERE `ID` = 2069;
UPDATE `mob_db` SET `kName` = "Piranha", `iName` = "Piranha" WHERE `ID` = 2070;
UPDATE `mob_db` SET `kName` = "Mula sem Cabeça", `iName` = "Mula sem Cabeça" WHERE `ID` = 2071;
UPDATE `mob_db` SET `kName` = "Espírito da Terra", `iName` = "Espírito da Terra" WHERE `ID` = 2072;
UPDATE `mob_db` SET `kName` = "Espírito do Ar", `iName` = "Espírito do Ar" WHERE `ID` = 2073;
UPDATE `mob_db` SET `kName` = "Curupira", `iName` = "Curupira" WHERE `ID` = 2074;
UPDATE `mob_db` SET `kName` = "Shadow of Deception", `iName` = "Shadow of Deception" WHERE `ID` = 2076;
UPDATE `mob_db` SET `kName` = "Shadow of Illusion", `iName` = "Shadow of Illusion" WHERE `ID` = 2077;
UPDATE `mob_db` SET `kName` = "Shadow of Pleasure", `iName` = "Shadow of Pleasure" WHERE `ID` = 2078;
UPDATE `mob_db` SET `kName` = "Hydra", `iName` = "Hydra" WHERE `ID` = 2081;
UPDATE `mob_db` SET `kName` = "Piranha", `iName` = "Piranha" WHERE `ID` = 2082;
UPDATE `mob_db` SET `kName` = "Zanzou", `iName` = "Zanzou" WHERE `ID` = 2308;